### ISSUE TITLE
sig#789 - Enhance the Servicerelease Technical-user-profile API to provide more information

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-backend#1007]
### Description

The API  `GET: /api/services/servicerelease/{serviceId}/technical-user-profiles` need to be enhanced to deliver the parameter 
`"type": "internal" | "external"`

### Acceptance Criteria

- [ ] API provides the `type`of technical user account 

### Test Cases 

**Test Case 1: Verify the type parameter for technical user accounts**
**Description**: Validate that the API GET: /api/services/servicerelease/{serviceId}/technical-user-profiles returns the type parameter with the value internal or external for each technical user account.
**Steps**:
Send a GET request to the API endpoint GET: /api/services/servicerelease/{serviceId}/technical-user-profiles.
Verify that the response contains the type parameter for each technical user account.
Ensure that the type parameter has a value of either internal or external.
**Expected Result:** The API response should include the type parameter for each technical user account, and the value should be either internal or external.

**Comment by Phil91** [comment]
@AnuragNagpure fyi I've taken over this issue.
