### ISSUE TITLE
sig#751 - Add BPDM Orchestrator Roles

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/portal-backend#1020]
### Description

As a Cx Operator I want to be able to create technical users with BPDM Orchestrator roles:

- BPDM Orchestrator Admin
- BPDM Orchestrator Task Creator
- BPDM Orchestrator Processor Clean
- BPDM Orchestrator Processor CleanAndSync
- BPDM Orchestrator Processor PoolSync

German Translations:

• BPDM Orchestrator Admin: Vollzugriff auf die Golden Record Tasks
• BPDM Orchestrator Task Creator: Erstelle Golden Record Tasks, lese das Task-Ergebnis und den Status aus
• PDM Orchestrator Processor Clean: Reserviere und bearbeitete Golden Record Tasks im Schritt 'Clean'
• BPDM Orchestrator Processor CleanAndSync: Reserviere und bearbeitete Golden Record Tasks im Schritt 'Clean And Sync'
• BPDM Orchestrator Processor PoolSync: eserviere und bearbeitete Golden Record Tasks im Schritt  'Pool'

Relevant references:
- [BPDM Permission documentation](https://github.com/eclipse-tractusx/bpdm/blob/release/6.1.x/docs/architecture/08_Crosscutting_Concepts.md)
- [IAM Issue for BPDM Update](https://github.com/eclipse-tractusx/portal-iam/issues/154)
- [IAM Pull Request for BPDM Udpate](https://github.com/eclipse-tractusx/portal-iam/pull/155)

### Acceptance Criteria

- [ ] Roles appear in technical user creation for the CX Operator
- [ ] Roles do not appear in technical user creation for any other Portal user role

**Comment by evegufy** [comment]
sig issue https://github.com/eclipse-tractusx/sig-release/issues/751

**Comment by evegufy** [comment]
Hi @typecastcloud great that you did implement https://github.com/eclipse-tractusx/portal-backend/pull/1002!
In general this change is quite similar, would it be possible that you take it over?

**Comment by typecastcloud** [comment]
> Hi @typecastcloud great that you did implement #1002! In general this change is quite similar, would it be possible that you take it over?

Okay I'll pick it up.

**Comment by evegufy** [comment]
Hi @typecastcloud I noticed the "new" service accounts from BPDM also need to be added to the Portal seeding ([service-account table](https://github.com/eclipse-tractusx/portal-backend/blob/main/src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_service_accounts.json), to operator company) :

- sa-cl7-cx-1
- sa-cl7-cx-7
- sa-cl25-cx-1
- sa-cl25-cx-2
- sa-cl25-cx-3

Would make sense to combine it with this issue.

**Comment by nicoprow** [comment]
Added german translations

**Comment by typecastcloud** [comment]
## Test Cases

### Test Case 1: Create Technical User - BPDM Orchestrator Admin
Description: Verify that technical user `BPDM Orchestrator Admin` with correct roles gets created by CX Operator
Steps:

- Go to technical user management
- Create "BPDM Orchestrator Admin"
- Create token
- Verify roles

Expected Result: 
```
"Cl25-CX-BPDM-Orchestrator": [
  "create_result_poolSync",
  "read_task",
  "create_result_cleanAndSync",
  "create_task",
  "create_reservation_clean",
  "create_reservation_poolSync",
  "create_result_clean",
  "create_reservation_cleanAndSync"
]
```
or compare roles with eclipse-tractusx/portal-iam#155

### Test Case 2: Limited CX Operator Company Access
Description: Verify that only CX Operator can create the new BPDM roles
Steps:

- Login to "non"-CX-Operator company
- Go to technical user management
- Check if any of the new roles or service accounts are are visible
Expected Result: 
No BPDM Orchestrator role of service account is available to create or update 

Test Case 3: Change secret via Portal
Description: Verify that secret for `sa-cl25-cx-3` can be reset
Steps:

- Go to technical user management
- Search for `sa-cl25-cx-3`
- Open details
- Create token to check if service account works
- Click on `Reset Credentials`
- Create token to check if service account still works

Expected Result: Secret is changed and works after reset
