### ISSUE TITLE
sig#789 - API Expansion for Role Information

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-backend#1022]
### Description

Expand the GET technical user information API to include the roletype (internal/external).
As an API Developer, I need to enhance the GET technical user information API to include the technical user type and service endpoint so that this information can be programmatically retrieved and utilized in various systems.

Endpoint to be adjusted -> `GET: api/administration/serviceaccount/user/roles`
Add Parameter `roleType` should display `internal` or `external`

### Acceptance Criteria

- [ ] The API should return whether the technical user is internal or external.

### Test Cases 
**Test Case 1: Retrieve technical role information - Internal**
Description: Verify that the API returns the correct technical role information.
**Steps:**
Make a GET request to the endpoint `api/administration/serviceaccount/user/roles`
Verify that the response includes the following fields:
RoleType: "internal"
**Expected Result:** The API should return the technical role information with the correct "internal" type 

**Test Case 2: Retrieve technical role information - External**
Description: Verify that the API returns the correct technical role information.
**Steps:**
Make a GET request to the endpoint `api/administration/serviceaccount/user/roles`
Verify that the response includes the following fields:
RoleType: "external"
**Expected Result:** The API should return the technical role information with the correct "external" type

**Comment by MaximilianHauer** [comment]
@gopalreddy-bmw  please verify against swagger

**Comment by gopalreddy-bmw** [comment]
Hi @MaximilianHauer 
i tested this ticket with @Phil91 it's working fine. Can you close this ticket.

Attached Screenshots for references
![image](https://github.com/user-attachments/assets/6e68975b-a51c-448a-8661-d76e1f7c8084)
![image](https://github.com/user-attachments/assets/55c011ff-91ce-4ab5-8cb5-628a4033b483)
