### ISSUE TITLE
Create a dedicated endpoint for the applicationRequests that enables a CX-Operator to access docs from other companies 

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-backend#1070]
### Description

Currently the endpoint `GET: /api/registration/documents/{documentId}` only response the document for the user which has uploaded the document. This check should be adjusted:

add a check if the requesting user is in a company which has the role `OPERATOR` if this is the case the user should be able to download the document.

the endpoint should check if the company application is not in "confirmed" otherwise it should raise a 403 "Documents not accessible as onboarding process finished"

### Acceptance Criteria

- [ ] Try to call the endpoint with an cx-operator role - the document should be downloaded 
- [ ] Try to call the endpoint with a role that is not cx-operator - you should receive an error message that your not allowed to access this endpoint 
- [ ] If the company's application is in the "confirmed" status, the endpoint should proceed with the document retrieval.
- [ ] If the company's application is not in the "confirmed" status, the endpoint should return a 403 HTTP status code with the message "Documents not accessible as onboarding process finished".

### Additional Information
The logic to be adjusted is `DocumentRepository` -> `GetDocumentIdWithCompanyUserCheckAsync` and `RegistrationBusinessLogic` -> `GetDocumentContentAsync`

**Comment by MaximilianHauer** [comment]
@gopalreddy-bmw  can you test this ?

**Comment by gopalreddy-bmw** [comment]
@MaximilianHauer Today i will test and close it.

**Comment by MaximilianHauer** [comment]
@gopalreddy-bmw  tested ?
