### ISSUE TITLE
External Technical User Callback fails

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-backend#1112]
### Current Behavior
When creating an external technical user, the callback of the dim-middle-layer fails due to duplicate tracking of the process steps

### Expected Behavior
When creating an external technical user the callback should succeed.

### Steps To Reproduce
Create an external technical user (technical user with user role `Identity Wallet Management`), wait for the callback. The callback fails.

**Comment by Phil91** [comment]
@evegufy fyi

**Comment by evegufy** [comment]
was introduced with https://github.com/eclipse-tractusx/portal-backend/pull/958, 2.3.0-alpha.1
