### ISSUE TITLE
Home Page | 'New Applications' Section Displays Apps Randomly Instead of the Most Recent Four Created

### ISSUE THREAD

**Issue by tfjanjua** [eclipse-tractusx/portal-backend#1131]
### Current Behavior
Apps are displayed in a random order rather than the most recent four created apps.

### Expected Behavior
The section should display the four most recently created apps, sorted by their release date.

### Steps To Reproduce
1. Login to Portal App.
2. Navigate to the portal home page.
3. Scroll to the 'New Apps' section.
4. Observe the order of the applications displayed.

**Comment by Phil91** [comment]
@tfjanjua in my opinion it would make sense to add a sortability to the apps  not sure if everyone wants the list to be ordered by the most recent release one. maybe one would sort by name or even subscriptions (not sure if that's really a case but think you get my point). But adding a sortability to the list would need frontend adjustments

@MaximilianHauer fyi, what's your opinion on that?

**Comment by tfjanjua** [comment]
@Phil91 , thanks for your feedback, I totally understand your point and I think its really ideal suggestion when this API is been responding data for a sortable list (like tabular list) but FE is been using this API's responded data to show the **New Apps** so I just thought maybe in this case we should get the ordered list from BE in anyways so, only New Apps could have been shown.

but lets wait for @MaximilianHauer response.

**Comment by ntruchsess** [comment]
@Phil91 @MaximilianHauer from my point of view we should merge https://github.com/eclipse-tractusx/portal-backend/pull/1132 as it is as having a predefined sorting order cannot be worse than having no defined sorting order at all (which is the case now).
Nevertheless we may consider @Phil91 's suggestion to add a parameter to the api that allows to define the sortingorder dynamically (we do have this in lots of other places and it's easy to implement, but obviously it requires frontend-changes to make a difference)
