### ISSUE TITLE
sig#882 - get overview of to be adjusted error messages

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-backend#1138]
### Description
To change the error messages to the new structure, an overview needs to be created. Therefor each service should be analysed for the usage of the old way to throw errors (e.g. throw new NotFoundException).

The business logic which uses the old way to throw an error should be included in a list or issue (if an issue is created please create a issue per service) 

### Acceptance Criteria

- [ ] Identify usages of throw new for all services (Administration.Service, Apps.Service, Services.Service, Notification.Service, Registration.Service)
- [ ] Create a List / Issues per Service with the classes that needs to be adjusted

**Comment by MaximilianHauer** [comment]
follow-up stories delivered
