### ISSUE TITLE
Filters are not functioning correctly

### ISSUE THREAD

**Issue by gopalreddy-bmw** [eclipse-tractusx/portal-backend#1199]
**Current Behaviour**
Filters are not working as expected

**Screenshot**
![image](https://github.com/user-attachments/assets/79c2edb9-276a-4bac-bfbf-10548ad43dcf)
![image](https://github.com/user-attachments/assets/fa717610-b18c-4ca6-be04-217bf7fb7a8b)
![Uploading image.png…]()

**Expected Behaviour**
Filters should be working as expected 

**Steps To Reproduce**
1.Login to https://portal.int.catena-x.net/technicalUserManagement
2.Click on show all 
3.Click on Managed filter and observe

**Comment by Phil91** [comment]
@MaximilianHauer @gopalreddy-bmw @lavanya-bmw the column ownership represents the type of the serviceAccount if it's managed by yourself or another company. The Owner checks is the company which queries the endpoint is either the owner or the provider, if one of the two is the case the owner is true. When selecting the owned flag the frontend filters for isOwner=true which filters the owner flag. That's the reason you're seeing technical users with ownership managed and own.

**Comment by MaximilianHauer** [comment]
Clarfield with @Phil91 , works as designed as the filter are focusing on column "Owner"
