### ISSUE TITLE
QG4: TRG 7.02 - License and Copyright header

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/portal-backend#220]
Hi @evegufy,

Few files missing Copyright headers:

Testing Quality Guideline: TRG 7.02 - License and Copyright header
Failed! Guideline description: Where possible, all source code should contain appropriate copyright and license notices as well as information on each contribution.
Can't find copyright headers at:

        src/administration/Administration.Service/Models/CompanyWithAddressData.cs
        src/administration/Administration.Service/Models/SsiCertificateData.cs
        src/externalsystems/Bpdm.Library/Models/BpdmSharingState.cs
        src/framework/Framework.Seeding/JsonHelper/SnakeCaseNamingPolicy.cs
        src/framework/Framework.Token/GetTokenSettings.cs
        src/marketplace/Apps.Service/Extensions/AppExtensions.cs
        src/marketplace/Offers.Library/Models/OfferDeclineRequest.cs
        src/portalbackend/PortalBackend.DBAccess/Models/AppUseCaseData.cs
        src/portalbackend/PortalBackend.DBAccess/Models/OfferDocumentContentData.cs
        src/portalbackend/PortalBackend.DBAccess/Models/OperatorBpnData.cs
        src/portalbackend/PortalBackend.PortalEntities/AuditEntities/AuditConnector20230405.cs
        src/portalbackend/PortalBackend.PortalEntities/AuditEntities/AuditConnector20230503.cs
        src/portalbackend/PortalBackend.PortalEntities/AuditEntities/AuditConnector20230803.cs
        src/portalbackend/PortalBackend.PortalEntities/AuditEntities/AuditIdentity20230526.cs
        src/portalbackend/PortalBackend.PortalEntities/Entities/Identity.cs
        src/portalbackend/PortalBackend.PortalEntities/Entities/OfferSubscriptionProcessData.cs
        src/portalbackend/PortalBackend.PortalEntities/Entities/VerifiedCredentialExternalType.cs
        src/portalbackend/PortalBackend.PortalEntities/Entities/VerifiedCredentialExternalTypeUseCaseDetailVersion.cs
        src/portalbackend/PortalBackend.PortalEntities/Enums/MediaTypeId.cs
        src/portalbackend/PortalBackend.PortalEntities/Enums/VerifiedCredentialExternalTypeId.cs
        src/provisioning/Provisioning.Library/Extensions/ProtocolMapperSettings.cs
        src/provisioning/Provisioning.Library/Models/CompanyNameIdpAliasData.cs
        tests/administration/Administration.Service.Tests/Usings.cs
        tests/framework/Framework.Web.Tests/Usings.cs
        tests/portalbackend/PortalBackend.DBAccess.Tests/ContentTypeMapperExtensionsTests.cs
        tests/portalbackend/PortalBackend.DBAccess.Tests/InvitationRepositoryTests.cs
        tests/portalbackend/PortalBackend.DBAccess.Tests/PortalDbContextTests.cs
        tests/provisioning/Provisioning.Library.Tests/FlurlSetup/FlurlSetupExtensions.cs

More infos: https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02

Updates https://github.com/eclipse-tractusx/portal-backend/issues/207

**Comment by evegufy** [comment]
Hi @tomaszbarwicki the file headers were added.
this file already had a header:
 src/administration/Administration.Service/Models/CompanyWithAddressData.cs
