### ISSUE TITLE
TRG 4.01 multiple container tags

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/portal-backend#358]
https://github.com/eclipse-tractusx/portal-backend/blob/v1.7.0-RC4/.github/workflows/release.yml#L65-L72

Example for the first image in workflow, applies to all other image builds as well.

release.yaml workflow doesn't create expected multiple container tags, like
- x
- x.y
- x.y.z

Instead, only x.y.z + latest tags will be created: https://hub.docker.com/r/tractusx/portal-administration-service/tags?page=1&name=v1

**Comment by evegufy** [comment]
@carslen Thanks for hint! we'll look into multiple container tags as an improvement for the release workflows for the next release. Please annotate that accordingly in https://github.com/eclipse-tractusx/portal-backend/issues/357.
As semantic versioning as well as tagging is in place, I'd suggest to rename the issue to 'TRG 4.01 multiple container tags'.
