### ISSUE TITLE
Store IdP UserID for reference and User Management 

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-backend#430]
For Managed and Own IdP Users; store the "ProviderUserID" inside the portal DB.

With that we enable the user to not only view the stored first, last name and email; but the actual user ID which is used to connect the user to the own/3rd party IdP.

The change will improve:
 * transparency
 * support the user in error cases 
 * allows us in future to also support "change" on the same

 

DB Change Proposal (several solutions are possible, the solution below is only a proposal)
 * add a new table which links an identity with the providerUserID (why a new table: because the user could have several IdPs linked; which means the user has multiple providerIds, to store them all we need to separate the information from the identities)

### ACCs

- [x] code changes done
- [x] pr created
- [x] review done
- [x] deployed to rc
- [x] successfully tested on rc
- [x] checked documentation update need and pr created/linked here (if necessary)

**Comment by ntruchsess** [comment]
PR #427 approved and merged

**Comment by jjeroch** [comment]
@Phil91 a couple on question after testing was done:

- ACC "documentation" is marked as "done" but couldn't find any docu in assets. Could you please check and link the pr here?
- I could see that we do not manage existing users regarding their providerID - we will need to manage this (open task)
- The pr is part of the RC4 - somehow the db on INT already includes the new field. Where/when was the db change published? Do we have this PR somewhere?

**Comment by Phil91** [comment]
@jjeroch 

- I'll double check the documentation, might be a misclick or I didn't pushed the changes.
- I missed that part, I'll think about how we could provide a logic to update existing users
- the PR to store the information was merged into RC4, the database part was already introduced by the NetworkRegistration #255 
- the endpoints are the following:

  Included the new information in the response:
    GET: api/administration/user/owncompany/users?page=0&amp;size=5
    GET: api/administration/user/owncompany/users/{userId}
    GET: api/administration/user/ownUser

  Database entry saved:
    POST: api/administration/identityprovider/owncompany/usersfile
    POST: api/administration/registration/network/{externalId}/partnerRegistration
    POST: api/administration/invitation
    POST: api/administration/user/owncompany/users
    POST: api/administration/user/owncompany/identityprovider/{identityProviderId}/users
    POST: api/administration/user/owncompany/identityprovider/{identityProviderId}/usersfile
    POST: api/administration/user/owncompany/usersfile
    Post: /api/registration/application/{applicationId}/inviteNewUser

- that's on me sorry. I totally forgot about that, should I revert the changes for the role response for now?.
