### ISSUE TITLE
Sonarcloud finding - remove unused code

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#437]
## Summary

clean-up - sonar findings of unused code created by previois pull requests
36 findings of not used code

Filter to find the findings: https://sonarcloud.io/project/issues?assignees=ntruchsess%40github&resolved=false&types=CODE_SMELL&id=catenax-ng_tx-portal-backend&open=AYZ5-LhVZcK8fwKW-DSh

Target: get rid of the 36 findings

**Comment by jjeroch** [comment]
Obsolete Endpoints to be removed

- POST: api/administration/identityprovider/owncompany/users/{companyUserID}/identityprovider
- GET /api/administration/user/app/{appId}/roles
- PUT /api/administration/user/app/{appId}/roles

**Comment by ntruchsess** [comment]
additional Endpoints that is marked obsolete:
POST: api/apps/autoSetup
POST: api/services/autoSetup

**Comment by ntruchsess** [comment]
Additional code that is marked as obsolete:
Entity-property 'Identity.UserEntityId' (maps to table 'identities', column 'user_entity_id')

**Comment by jjeroch** [comment]
> additional Endpoints that is marked obsolete: POST: api/apps/autoSetup POST: api/services/autoSetup

Both are still needed since we have active customer integration on those.
Plan: delete in 24.05.

**Comment by ntruchsess** [comment]
implemented in PR https://github.com/eclipse-tractusx/portal-backend/pull/531
This PR also contains fixes for all findings from codeql that technically could be fixed ( https://github.com/eclipse-tractusx/portal-backend/security/code-scanning?query=is%3Aopen+tool%3ACodeQL+branch%3Achore%2Fintroduce-codeql-check-fix ).

**Comment by ntruchsess** [comment]
Pr #531 is approved and merged. Deployment on dev was successful
