### ISSUE TITLE
Application Request Decline - 502 error

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#451]
Detected in version: **v.1.8.0 RC3**

## Summary

Running the https://portal-backend.int.demo.catena-x.net/api/administration/registration/applications/{applicationID}/decline endpoint results into a 502 error

Response on specific test data

- env: INT
- application id: 6fb382a3-c25b-4767-be5c-07274f0adf40

`Org.Eclipse.TractusX.Portal.Backend.Keycloak.ErrorHandling
: 
["remote service returned status code: 403 Forbidden",…]
0
: 
"remote service returned status code: 403 Forbidden"
1
: 
"Forbidden: https://sharedidp.int.demo.catena-x.net/auth/admin/realms/idp71"`

**Comment by Phil91** [comment]
figured out the issue, the user which deletes the realm from keycloak is missing a role.
