### ISSUE TITLE
PartnerRegistration - POST Partner Data runs on 403 error

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#457]
Detected in version: **v.1.8.0 RC3**

### Summary
The job POSTPartnerRegistration runs on a 403 error with the user sa171 (secrets available on INT centralIdP)

Possible issue: endpoint validation

Test Execution: on INT via swagger

**Comment by Phil91** [comment]
@jjeroch  you mean the endpoint: `POST: api/administration/registration/network/partnerRegistration` right?

**Comment by Phil91** [comment]
The seeded data of keycloak have been fixed for all environments.

**Comment by Phil91** [comment]
sucessfully tested on rc.
