### ISSUE TITLE
Test Automation Script - enable rc.dev run

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#460]
### Summary
Enable the run of the test automation script on rc.dev env.

### Acceptance Criteria

- [ ] change applies
- [ ] workflow supports rc.dev
- [ ] updated asset docu about the additional env. supported https://github.com/catenax-ng/tx-portal-assets/blob/main/docs/developer/Technical%20Documentation/Tests/Automation/01.%20Summary.md
- [ ] deployed
- [ ] test run successfully executed (meaning that the run was executed on the respective env. and authentication was successful)

**Comment by jjeroch** [comment]
back to backlog

**Comment by evegufy** [comment]
should be validated if still needed as consortia envs will be deprecated soon
