### ISSUE TITLE
API: POST Company Certificates

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#468]
### Summary

POST Company Certificate endpoint needed which created a db record of an company certificate uploaded incl. the document storage itself

_the implementation of this ticket depends on https://github.com/eclipse-tractusx/portal-backend/issues/471_

 

### Detail

Suggested API Endpoint: POST /api/administration/companydata/companyCertificate

Request Parameter:
 * media file  (uploaded by the user)
 * certificate type (provided by the frontend - this is the certificate type which is available under the new table + #471 "company_certificate_types") - use the string value of the enum type
 * expiry date (format: yyyy-mm-dd)

Only PDF is allowed and up to 2MB file size

When the POST endpoint is triggered, following activities are executed:
 * document is getting stored inside the documents table 
   * id: new given uuid
   * date_created: upload timestamp 
   * document_hash: document hash
   * document_name: name of the document file
   * document_type_id: always id "15"
   * document_status_id: always "locked"
   * company_user_id: user uploaded the file
   * media_type_id: media type given by the file (content type of the file)
   * date_last_changed: upload timestamp 
   * last_editor_id: user uploaded the file
 * company_certificate table is getting filled and new uploaded document_id is added
   * valid from date is set with the current timestamp
   * type: depending on the type submitted
   * expiry date: handed over by FE or null

 

### Validation:
 * Acting user must have the role „upload_certificates“ assigned

 

### Related Tickets
----
DB Changes to enable the feature: https://github.com/eclipse-tractusx/portal-backend/issues/471

FrontEnd-Implementation Ticket: CPLP-3662

Backend API Development CPLP-3655, CPLP-3656

---

_Components_: N/A
_Sprints_:  PI 12 - S1 - CPLP
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: [CPLP-3657-image-2023-12-27-13-15-51-660.png](https://jira.catena-x.net/secure/attachment/23546/image-2023-12-27-13-15-51-660.png), [CPLP-3657-image-2023-12-27-13-37-47-123.png](https://jira.catena-x.net/secure/attachment/23547/image-2023-12-27-13-37-47-123.png)

**Comment by AnuragNagpure** [comment]
https://github.com/eclipse-tractusx/portal-cd/pull/174

**Comment by Phil91** [comment]
Not sure if I understand the ticket correctly, so I summarise my understanding:

The endpoint should provide the possibility to create a company certificate while uploading a document at the same time.

@jjeroch correct?

Then we should remove the certificateId from the url since we're creating the certificate and therefore no id is available.
If the ticket should only upload the document the description needs some updates

**Comment by jjeroch** [comment]
@Phil91 right - the endpoint is used to create the company certificate record in the portal db and automatically also stores the document itself inside the document table. 
The certificateID is probably a wrong naming from my side - what I wanna state here is the certificate type:

<img width="393" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/94133633/cfcec5ae-1908-4b68-8356-7d8489948008">

or would you add this inside the POST endpoint?

**Comment by jjeroch** [comment]
ok I understood - we have the company certificate type in the body so we can change the 
Endpoint Path 
from: POST /api/administration/companydata/companyCertificate/\{certificateId}/document
to: POST /api/administration/companydata/companyCertificate

**Comment by Phil91** [comment]
successfully tested on the rc environment

**Comment by jjeroch** [comment]
@AnuragNagpure can you please recheck the implementation.
As per the description the document is supposed to get uploaded in status: document_status_id: "locked"

Can you please recheck this once and in case this is not yet implemented please raise a pr against the dev branch

**Comment by jjeroch** [comment]
@AnuragNagpure  is the comment above already solved?

**Comment by AnuragNagpure** [comment]
@jjeroch  No it needs to merge as #462 and #463 merging is pending after this that changes will get merged.
