### ISSUE TITLE
API: GET Certificate Types

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#469]
### Summary

Static Data Endpoint to retrieve supported certificate types

_the implementation of this ticket depends on https://github.com/eclipse-tractusx/portal-backend/issues/471_

 

### Detail

Suggested API Endpoint: GET /api/administration/staticdata/certificateTypes

 

Response Body

```
[
  {
    "companyCertificateId": "{company_certificate_type.id}",
    "name": "{company_certificate_types.label}",
    "description": [
      {
        "language": "{company_certificate_types_description.language_short_name}",
        "longDescription": "{company_certificate_types_description.description}"
      }
    ]
   }
] 
```
 

### Validation:
 * Acting user must have the role „view_certificates“ assigned

 

### Related Tickets
----
DB Changes to enable the feature: https://github.com/eclipse-tractusx/portal-backend/issues/471

FrontEnd-Implementation Ticket: CPLP-3641

---

_Components_: N/A
_Sprints_: PI 12 - S1 - CPLP
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: [CPLP-3656-image-2023-12-27-13-15-51-660.png](https://jira.catena-x.net/secure/attachment/23544/image-2023-12-27-13-15-51-660.png), [CPLP-3656-image-2023-12-27-13-37-47-123.png](https://jira.catena-x.net/secure/attachment/23545/image-2023-12-27-13-37-47-123.png)

**Comment by ntruchsess** [comment]
PR is approved and merged.
implemented endpoint is:
GET /api/administration/staticdata/certificateTypes
```
[
  {
    "certificateType": "AEO_CTPAT_Security_Declaration",
    "description": [
      {
        "languageShortName": "string",
        "description": "string"
      }
    ]
  }
]
```
