### ISSUE TITLE
API: GET Company Certificates

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#470]
### Summary

Enable companies to fetch their company certificates with the respective document status

_the implementation of this ticket depends on https://github.com/eclipse-tractusx/portal-backend/issues/471_

 

### Detail

Suggested API Endpoint: GET /api/administration/companydata/companyCertificates

 

Response Body

```
[
  {
    "companyCertificateType": "{company_certificate.company_certificate_type as label}",
    "companyCertificateStatus": "{company_certificate.status as label}",
    "documentId": "uuid",
    "validFrom": "{valid_from}",
    "validTill": "{valid_till}"
  }
]

```
 

### Business Logic of the /companyCertificates endpoint

 
 * fetch all company certificate records from the table "company_certificates"
 * make sure that only those records are responded, where the company certificate is linked to the users company; how:
 ** use the method to get via the user_id to the company_id
 ** with the company_id go to table company_certificates and fetch all certificates linked to the same company_id

 

Supported features:
 * Filter: by status; certificate type
 * Sorting: certificate type, expiry date
 * Pagination
 

### Validation:
 * Acting user must have the role „view_certificates“ assigned

### Related Tickets
----
DB Changes to enable the feature: https://github.com/eclipse-tractusx/portal-backend/issues/471

FrontEnd-Implementation Ticket: CPLP-3641

---

_Components_: N/A
_Sprints_: PI 12 - S1 - CPLP
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: [CPLP-3643-image-2023-12-27-13-15-51-660.png](https://jira.catena-x.net/secure/attachment/23478/image-2023-12-27-13-15-51-660.png), [CPLP-3643-image-2023-12-27-13-37-47-123.png](https://jira.catena-x.net/secure/attachment/23479/image-2023-12-27-13-37-47-123.png)

**Comment by jjeroch** [comment]
@AnuragNagpure please fix the swagger docu - for the endpoint an incorrect example body is displayed:
<img width="1226" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/94133633/a4a7e3c0-07bb-41bb-bbca-6d2a6c59b980">

**Comment by AnuragNagpure** [comment]
> @AnuragNagpure please fix the swagger docu - for the endpoint an incorrect example body is displayed: <img alt="image" width="1226" src="https://private-user-images.githubusercontent.com/94133633/308816405-a4a7e3c0-07bb-41bb-bbca-6d2a6c59b980.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxODc5ODMsIm5iZiI6MTcwOTE4NzY4MywicGF0aCI6Ii85NDEzMzYzMy8zMDg4MTY0MDUtYTRhN2UzYzAtMDdiYi00MWJiLWJiY2EtNmQyYTZjNTliOTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA2MjEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyM2E3ZDI1NDM4NTRkOWVhODczMmNiYzMwODMxM2JlOWM5NmJiYmE4NDZmOTFlZmY4NjEzYzNiMDAwZjNjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9SO2MBAQ_dBl-Qzdrxv2qGoHBMGVRxmCsUEfjsSbZHk">

sure

**Comment by AnuragNagpure** [comment]
@jjeroch Swagger doc is updated with proper schema below is screenshot after updating and merging

![image](https://github.com/eclipse-tractusx/portal-backend/assets/145100366/c5dd7c43-6f0f-4641-88a0-11332270a457)

**Comment by AnuragNagpure** [comment]
@jjeroch Swagger schema doc fix is done below is updated schema screenshot
![Uploading image.png…]()
