### ISSUE TITLE
DB Enablement Company Certificates

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#471]
### Summary

Enable companies to fetch their company certificates with the respective document status.

To ensure that the feature can get supported, first changes on db level are needed ++ seeding data adjustments.

 

### Details

[CPLP-3642-image-2024-01-10-18-05-29-177.png](https://jira.catena-x.net/secure/attachment/23543/image-2024-01-10-18-05-29-177.png)

 

+DB Table Adjustments+ 

- [ ] new table "company_certificate_types" needed; with following attributes
 * id
 * label
 * status (linked to portal.company_certificate_type_status)

- [ ] new table "company_certificate_status" needed; with following attributes
 * id
 * label

- [ ] new table "company_certificate_type_description" needed; with following attributes
 * id
 * language_short_name
 * description

- [ ] new table "company_certificates" needed; with following attributes
 * company_id (link to portal.companies)
 * company certificate type (link to portal.company_certificate_types)
 * status (link to portal.company_certificate_status)
 * document_id (link to portal.documents)
 * valid from
 * valid till

 

 

### Seeding Data

- [ ] seeding data for the new table "company_certificate_types" 

ID | Company Certificate Types | Status
--|--|--
1 | AEO, CTPAT, Security Declaration | 1
2 | ISO 9001 | 1
3 | IATF 16949 | 1
4 | ISO 14001, EMAS or national certification | 1
5 | ISO 45001, OHSAS 18001 or national certification | 1
6 | ISO/IEC 27001 | 1
7 | ISO 50001 or national certification | 1
8 | ISO/IEC 17025 | 1
9 | ISO 15504 (SPICE) | 1
10 | B-BBEE Certificate of South Africa | 1
11 | IATF | 1
12 | TISAX | 1

- [ ] seeding data for the new table "company_certificate_type_status" 

ID | Status 
--|--
1 | ACTIVE
2 | INACTVIE

- [ ] seeding data for the new table "company_certificate_status" 

ID | Status 
--|--
1 | IN_REVIEW
2 | ACTIVE
3 | INACTVIE

- [ ] seeding data for the new table "company_certificate_type_description" 

ID | language_short_name | description
--|--|--
1 | de | Internationales Gütesiegel, das von der Zollbehörde an Unternehmen verliehen wird, die in der internationalen Lieferkette tätig sind.
1 | en | International seal of quality awarded by customs authorities to companies active in the international supply chain.
2 | de | Internationaler Standard, der Anforderungen an ein Qualitätsmanagementsystem (QMS) festlegt.
2 | en | International standard that specifies requirements for a quality management system (QMS).
3 | de | Zeigt, dass Ihr Unternehmen umfangreiche Anforderungen zur Schaffung eines kontinuierlichen Verbesserungsprozesses mit Schwerpunkt auf Fehlervermeidung und Reduzierung von Abweichungen und Verschwendung in der Lieferkette erfüllt hat.
3 | en | Demonstrates that your company has met extensive requirements to create a process of continuous improvement with an emphasis on defect prevention and reduction of variation and waste in the supply chain.
4 | de | Stellt Anforderungen mit Anwendungshinweisen bereit, die sich auf Umweltmanagementsysteme beziehen.
4 | en | Provides requirements with guidance for use that relate to environmental management systems.
5 | de | Internationaler Standard für Gesundheit und Sicherheit am Arbeitsplatz, herausgegeben zum Schutz von Mitarbeitern und Besuchern vor arbeitsbedingten Unfällen und Krankheiten.
5 | en | International standard for occupational health and safety, issued to protect employees and visitors from work-related accidents and diseases.
6 | de | Internationaler Standard für Informationssicherheit. Es legt die Vorgaben für ein wirksames ISMS (Informationssicherheitsmanagementsystem) fest.
6 | en | International standard for information security. It sets out the specification for an effective ISMS (information security management system).
7 | de | Freiwilliger Standard – erleichtert die Integration des Energiemanagements in die Gesamtbemühungen zur Verbesserung des Qualitäts- und Umweltmanagements.
7 | en | Voluntary standard - ease integration of energy management into overall efforts to improve quality and environmental management.
8 | de | Internationale Norm, die Anforderungen an Qualität und Kompetenz in Prüf- und Kalibrierlaboratorien festlegt.
8 | en | International standard specifying requirements for quality and competence in testing and calibration laboratories.
9 | de | Internationaler Standard zur Bewertung von Geschäftsprozessen durch entsprechende Assessments.
9 | en | International standard for the evaluation of business processes through corresponding assessments.
10 | de | Zertifikat zur Bestätigung der Unternehmensleistung im Hinblick auf die wirtschaftliche Stärkung der Schwarzen in Südafrika.
10 | en | Certificate verifying business' performance with regards to black economic empowerment in South Africa.
11 | de | Eine verbindliche Branchenanforderung, die Qualitätsmanagementsysteme für die Automobilindustrie weltweit anpasst.
11 | en | A mandatory industry requirement which aligns automotive quality management systems throughout the world.
12 | de | TISAX ist ein Bewertungs- und Austauschmechanismus für die Informationssicherheit von Unternehmen und ermöglicht die Anerkennung von Bewertungsergebnissen unter den Teilnehmern.
12 | en | TISAX is an assessment and exchange mechanism for the information security of enterprises and allows recognition of assessment results among the participants.

 

[ ]( ) seeding data for the existing table "document_types" 

ID | Label
--|--
15 | Company_Certificate

 
---
 

FrontEnd-Implementation Ticket: CPLP-3641
BackEndAPI-Implementation Ticket: CPLP-3643

---

_Components_: N/A
_Sprints_: PI 12 - S1 - CPLP
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: [CPLP-3642-image-2023-12-27-13-15-51-660.png](https://jira.catena-x.net/secure/attachment/23476/image-2023-12-27-13-15-51-660.png), [CPLP-3642-image-2023-12-27-13-37-47-123.png](https://jira.catena-x.net/secure/attachment/23477/image-2023-12-27-13-37-47-123.png), [CPLP-3642-image-2024-01-10-17-07-15-006.png](https://jira.catena-x.net/secure/attachment/23542/image-2024-01-10-17-07-15-006.png)

**Comment by AnuragNagpure** [comment]
PR Raised https://github.com/eclipse-tractusx/portal-backend/pull/475

**Comment by ntruchsess** [comment]
To separate data defined in code (enum) from data that can be updated at runtime:
added table:
company_certificate_type_assigned_statuses
columns:
company_certificate_type_id,
company_certificate_type_status_id
(data is been seeded from company_certificate_type_assigned_statuses.json), Insert- and Update-seeder have been defined.

**Comment by ntruchsess** [comment]
question: shall company_certificate<->document relation be 1<->1 or 1<->N?
(currently in code and schema it is defined as 1<->N)
