### ISSUE TITLE
SSI Flow - Middle Layer/Wrapper of DIM functions

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#479]
### Summary

```
! TICKET UPDATE ONGOING!!!!
```

develop a wrapper (must be release configurable) which wrappes wallet specific functions

<img width="857" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/94133633/b0158735-5f52-4ae7-a76e-938555791804">

...details to be added...currently under validation

#### Pre-Requ.

the wrapper needs a config file including the 
  - DIM hostname 
  - DIM Auth token url
  - directoryAdmin Email address (note we need a different admin address in the release file compared to the test file) -> for the test file configure functional lead developer and PO
  - globalAccount displayName (note we need a different admin address in the release file compared to the test file) -> for the test file configure 'CX-Operation Customers'
  - as well as vault connection where the technical user details are stored

the wrapper itself should cover the following endpoint triggers:

```
! Please note: Step 1 & 2 is only needed once (basically after an env. refresh if no global account was created yet).
```

1. GET /gloablAccount
2. POST /parentGUID={your parent GUID}
```
{
  "description": "API generated BTP directory",
  "directoryAdmins": [
    "{email}" //fetched from the env. config file
  ],
  "displayName": "CX-Operation Customers", //fetched from the env. config file
  "labels": {
    "cloud_management_service": [
      "Created by API - Don't change it"
] }
}
```
3. Store the new created Directory GUID (where? tbd)

4. Create the customer sub-Account inside the wallet

```
{
  "betaEnabled": false,
  "description": "CX customer sub-account {companyName}",  //to be created automatically by static text + company name
  "displayName": "{companies.business_partner_number}_{companies.name}",  // TenantName of #453 
  "labels": {
    "Cloud Management Service": [
      "Created by API - Don't change it"
    ],
    "tea_validity": [
      "Maximum 90 days"
    ] },
  "origin": "API",
  "parentGUID": "{{get_global_account_info.response.body.guid}}", // add the stored gloabl account GUID
  "region": "eu12",
  "subaccountAdmins": [ 
      "{email}" //fetched from the env. config file
    ],
  "subdomain": "test01",  // Change this
  "usedForProduction": "PRODUCTION"
}
```

5. Create a serviceManagerBinding (only needed for new GlobalAccounts - otherwise existing) 

```
details unknown
```

6. Store tech. user details

```
details unknown
```

7.  add cloudServiceManagement instance

```
details unknown
```

Note - from the description received from the DIM provider following tasks are not relevant:
- adding entitlements should be not relevant
- applicationSubscription not needed
- CF not needed
- applicationUsers

As soon as this is done, the service needs to proceed with setting up the tenant details.

**Comment by Phil91** [comment]
The new repo was requested:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4322
