### ISSUE TITLE
OSP Partner Invite | extId property pattern update needed

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#482]
Detected in version: **1.8.0 RC1**
*likely the issue exists since 1.7.0

### Summary

Connected to the FE ticket: https://jira.catena-x.net/browse/CPLP-3763
In the current implementation an extID "123456" runs on an error
`ExtID must be 6-36 digits long`
although the submitted ID was 6 characters long

=> please recheck the pattern. Everything between 6 and 36 characters should be allowed (incl. uuid characters, digits, letters, etc)

**Comment by Phil91** [comment]
@jjeroch I just checked the backend implementation, 123456 is possible as external id
