### ISSUE TITLE
ExternalIdP - User Account Creation Email

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#483]
### Summary

In the case of an user account creation under a ownIdP or managedIdP; as well as the migration of an user to the ownIdP/managedIdP should initiate the user notification via email 

- "migrate" an existing user account by adding an ownIdP userID (user email notification needed)
- create a new user account under ownIdP (user email notification needed)

the following email is supposed to get send:
https://github.com/eclipse-tractusx/portal-backend/blob/main/src/mailing/Mailing.Template/EmailTemplates/new_user_account_ownidp.html
*Note - via the FE ticket linked below the email template name is getting changed

Additionally the email gets 2 dynamic values added:

- url (already configured inside the email template - please reconfirm with FE the current value)
- tenantName / {idpAlias} (name used in another email template)

Connected Tickets: https://github.com/eclipse-tractusx/portal-frontend/issues/476

**Comment by ntruchsess** [comment]
implemented in https://github.com/eclipse-tractusx/portal-backend/pull/537
PR is approved and merged
