### ISSUE TITLE
Services Service - Allow Service Release without technicalUserProfile

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#499]
### Summary
The current implementation the service release process (dataspace services) at least 1 technical user role is expected to be selected to connect the service to central applications.
Till now a technical user was mandatorily needed - BUT changed recently and we need to allow with 24.05. that an user can release an dataspace service even without technical user connection.

To allow the same on backend side, following endpoints need to get adjusted:

- PUT /api/services/ServiceReleaseProcess/{serviceId}/submit

Update the endpoint business logic - in the current implementation the technicalUserProfile is set as MUST to allow the user to run PUT /api/services/ServiceReleaseProcess/{serviceId}/submit for a specific service.
This logic needs to get removed. It is allowed to submit an service request without technicalUserProfile configured

`Note the services service is getting updated as well - described in ticket: https://github.com/eclipse-tractusx/portal-backend/issues/497`

Linked FE ticket: https://github.com/eclipse-tractusx/portal-frontend/issues/501

**Comment by AnuragNagpure** [comment]
@jjeroch Technical user profile check is not present for services release process. Repository changes is done with #497 ticket PR #566 which is common for both apps and services.

**Comment by AnuragNagpure** [comment]
@jjeroch #566 PR is merged. As this ticket is also linked with #497 ticket implementation changing in review state
