### ISSUE TITLE
Swagger Docu - Apps

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#501]
### Summary
Incorrect swagger docu

### Details

Endpoint: GET /api/Apps/{appId}/subscription/{subscriptionId}/provider
Wrong example value displayed inside the response ""processStepTypeId": "VERIFY_REGISTRATION"" 
VERIFY_REGISTRATION has nothing to do with the app process

Same applies for the schema details below:
<img width="1384" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/94133633/e7ce39f2-a00e-4663-a104-2f9f02b0622f">

**Comment by Phil91** [comment]
@MaximilianHauer I'd like to discuss this topic with you, since it's not really possible to only display specific enum value in swagger. I guess it's possible that we edit the example with a few changes, but that's it.

**Comment by MaximilianHauer** [comment]
based on discussion this is not a technical fault but the way how swagger displays these enum.
it can be confusing if only swagger is reviewed but the options to adjust it do not fit in regards of Benefit:Risk.
