### ISSUE TITLE
..validate external didLocation

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#517]
`ticket in creation`

add on to #453 

validate the received
did id

**2 Scenarios**

1. Portal didLocation

2. Customer didLocation
"did:web:{customer-specific-url}" whether the did resolves to an didDocument using a third party resolver like https://dev.uniresolver.io/ 

validate that the did resolves to an didDocument using a third party resolver like https://dev.uniresolver.io/
If the validation is successful; set the newly created process step to done.
In case the validation did run on a fail:

- for portal did - set the process step to "failed"
- for customer did - re-run the resolver check after ab given time (ideally once a day); however a max_time needs to get defined (proposal 7 days) afterwards the process is getting set to failed

**Comment by Phil91** [comment]
The current implemented logic is as follows

1. Create the wallet through the DIM Middle Layer
2. Receive the callback of the DIM Middle Layer
  a. Validate the format of the did
  b. Validate the schema of the did document with the schemas given in the portal
  c. Publish the did document
3. Validate the did document with the universal resolver - if the validation isn't successful we will retry the up to x days. Where x is a configureable time.
