### ISSUE TITLE
User Admin and My CX Account: Personal and issuer information not shown

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal-backend#520]
### Current Behavior

<img width="405" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/46191613/505bf8cd-89bf-41a1-b905-2b731ca406a4">
<img width="410" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/46191613/5285e92b-bf8f-409a-903a-636226272d9d">

### Expected Behavior

Personal and issuer is shown

### Steps To Reproduce

defected in v1.8.0-RC5

**Comment by jjeroch** [comment]
Validation done - the endpoint does not send the users firstname, lastname, etc. 
Example from INT
calling via the test operator account the following endpoint: /api/administration/user/owncompany/users/8e10dadc-ed35-4e39-88c9-1c25c4dee1f7
Response:

` 
   "firstName": null,
    "lastName": null,
    "email": null
`

while on db level data are existing

**Comment by ntruchsess** [comment]
the bug was introduced with PR #427
from code-analysis: endpoint GET /api/administration/user/ownUser is also affected.

**Comment by evegufy** [comment]
successfully retested
