### ISSUE TITLE
Cleanup Test Seeding Data

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#524]
### Summary

Cleanup of the test seeding data consortia needed.
Additionally we might need to re-name the files since consortia wont make much sense anymore by may this year

Special Focus:

- users (real users, technical users)
- realms
- companies
- etc.

`Note: ticket still in refinement`

=> CX Operator: assign role company admin
=> recheck of all company accounts - we wont need all of this anymore; likely we can reduce to 3-4 companies
  - CX Operator
  - OSP Login (plays the external IdP) - 10 user accounts likely needed
  - Security
  - CX-Test-Access (as company; not as operator)

`Note - the change will impact our seeding data as well as the keycloak image`

---

Julia Notes:

- remove `sa-cl5-custodian-3` => inform MIW; likely they dont even know this user
- remove `sa-cl5-custodian-4` => inform MIW; likely they dont even know this user
- remove `Cl9-CDQ-Fraud` => inform BPDM; likely they dont even know this user anymore
- remove `Cl12-CX-TestManager` => inform TMs to inform TestDataFile creation team; likely they dont even know this user
- renaming of `Cl5-CX-Custodian` needed to `Cl5-CX-DigitalWallet needed`. Attention the renaming might impact the FE as well as the MIW Team
- remove `sa-beta-cx1`
- remove `sa-beta-cx2`
- remove `sa-beta-cx3`
- remove `sa-beta-cx4`
- remove `sa-beta-cx5`
- remove `sa-beta-cx6`
- remove `sa-beta-cx7`
- change user `sa-cl5-custodian-internaltest` to `sa-cl5-digitalwallet` and provide user to MIW team - they will use the user for tests and testsloads

....note, the deletion will impact seeding as well as the portal DB

---

**Consortia Test Data Set**
- to be renamed to "TestData" instead of "Consortia"
- Update of all `usernames` inside keycloak needed for the following test users (new `username` to be fetched from the portal db portal.identities `id`)

  | app-provider.aa4b2a5d-2dc7-419c-a8ce-72886e0e32e9 | app-provider@cx.com | App Provider | Tester | 
  | company-1.03b7feab-cc55-48cd-882a-0d8db03a8c8c | company.admin@cx.com | Company Admin | Test User |  
  | company-2.a81a425e-bdb4-482b-8535-a02c313c25af | companyadmin@cx.com | Company Admin | Test User |   
  | cx-test-access.08132c4c-146d-41ee-938a-09759783eea1 | company2@user.de | company 2 | user |  
  | cx-test-access.0f3abd37-9b87-421c-81e7-14a612bab68c | cxuser@cx.com | CX User | Test User |
  | cx-test-access.311963ed-9c58-44a6-8103-0b689cebaeaa | partchain.three@cx.de | PartChain Three | Tester |  
  | cx-test-access.3d0f5663-2de1-4a08-a394-22d1d4248efc | partchain.one@cx.de | PartChain One | Tester |
  | cx-test-access.6f25fc27-a5ec-4ad8-bd89-e05ca462c741 | cxadmin@cx.com | CX Admin | Test User | 
  | cx-test-access.98715874-e65c-4780-95ad-fb4e8eb917a8 | company1@user.de | company 1 | user |
  | cx-test-access.a0661e13-c74c-4b86-8151-ed1c348d0e69 | companyadmin@cx.com | Company Admin | Test User |
  | cx-test-access.f3d5e0c6-bb7b-4bb2-963f-3daffc90328d | partchain.two@cx.de | PartChain Two | Tester |
  | cx-test-access.f58e4a43-c560-443d-9b1e-fcb182682bcb | itadmin@cx.com | IT Admin | Test User |
  | security-company.18f1a488-06e9-4dc4-ad43-cfb9c9a0c7db | cxuser-1@cx.com | CX User 1 | Test User 1 |
  | security-company.22b92584-895a-442f-afe9-ed10fe997d95 | companyadmin-1@cx.com | Company Admin 1 | Test User 1 |
  | security-company.3d064630-3736-477e-80e2-148faf1cd211 | itadmin-1@cx.com | IT Admin 1 | Test User 1 | 
  | security-company.4746cff4-7a64-4be8-a70e-cf762a7011b8 | itadmin-2@cx.com | IT Admin 2 | Test User 2 |
  | security-company.555b0b81-6ead-4d3d-8d5d-41c07bb8cfbc | cxadmin-1@cx.com | CX Admin 1 | Test User 1 |  
  | security-company.8b747479-5e22-4e9c-a0a4-a940e8ec0536 | cxuser-2@cx.com | CX User 2 | Test User 2 | 
  | security-company.cc860ece-ede3-4c03-86f9-28e23978b105 | cxadmin-2@cx.com | CX Admin 2 | Test User 2 |
  | security-company.e5e403d5-3bd9-48f6-8931-7c0c717c3f41 | companyadmin-2@cx.com | Company Admin 2 | Test User 2 |

**Comment by evegufy** [comment]
the following clean ups are done:
- remove `sa-cl5-custodian-3`
- remove `sa-cl5-custodian-4`
- remove `Cl9-CDQ-Fraud`
- remove `Cl12-CX-TestManager`
- remove `sa-beta-cx1`
- remove `sa-beta-cx2`
- remove `sa-beta-cx3`
- remove `sa-beta-cx4`
- remove `sa-beta-cx5`
- remove `sa-beta-cx6`
- remove `sa-beta-cx7`

**Comment by jjeroch** [comment]
Decision: we do not loger maintaine the test data anymore - closing the ticket with "wont do" further actions are taken up in https://github.com/eclipse-tractusx/portal/issues/349
