### ISSUE TITLE
Not able to cancel user application request

### ISSUE THREAD

**Issue by johanneskueffner** [eclipse-tractusx/portal-backend#525]
### Current Behavior
When trying to cancel an application request, the portal shows an error 
![image](https://github.com/eclipse-tractusx/portal-backend/assets/71873124/cf499984-99d2-4880-ba33-f662a41946d0)

The console shows the following error:
```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "errors": {
        "unknown": [
            "Bad Request: https://sharedidp.int.demo.catena-x.net/auth/admin/realms/idp99"
        ],
        "Flurl.Http": [
            "Call failed with status code 400 (Bad Request): DELETE https://sharedidp.int.demo.catena-x.net/auth/admin/realms/idp99"
        ]
    },
    "errorId": "872daf59-fd6a-464f-9911-c90b76a324d2",
    "details": []
}
```

### Expected Behavior
The operator is able to successfuly cancel an application

### Steps To Reproduce
Try to cancel any ongoing request in the admin board

**Comment by jjeroch** [comment]
Env.: INT

**Comment by Phil91** [comment]
@johanneskueffner could you please add the endpoint which is called as well?

**Comment by jjeroch** [comment]
Endpoint: https://github.com/eclipse-tractusx/portal-backend/issues/525

**Comment by Phil91** [comment]
Deployed and tested on dev-rc
