### ISSUE TITLE
Administration Service - Connector Controller - delete connector logic

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#547]
### Summary
Update Connector controller and respective api endpoint bodies due to latest changes made in the SSINext solution

### Details

**Endpoint:** `/api/administration/Connectors/{connectorId}`

**Method:** `DELETE`

**Needed changes:**
- tbd

---

**Comment by MaximilianHauer** [comment]
https://github.com/eclipse-tractusx/portal-backend/issues/550 closed as wont do
