### ISSUE TITLE
Administration Service - Connector Controller change connector URL

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#549]
### Summary
Recheck and enhancement of the current existing PUT endpoint(s) for connector controller

### Details

**Endpoint:** `/api/administration/Connectors/{connectorId}/connectorUrl`

**Method:** `PUT`

**Needed changes:**
- Implementation of following backend logic:
  - with the endpoint trigger, the backend logic will set the current connector assigned self-description to "INACTIVE" - no matter which status the document has currently (retrieve via the table `portal.connectors` the linked self-description document from the attribute connectors.self_description_document_id
  - open the table `portal.documents`, search for the connectors.self_description_document_id inside the field `id` and set the status to "INACTIVE" 
  - now trigger the SD factory endpoint (same as triggered for the POST `/api/administration/Connectors` - functional details: https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/02.%20Technical%20Integration/01.%20Connector%20Registration/05.%20Self%20Description.md) and submit the relevant data

**Comment by AnuragNagpure** [comment]
@jjeroch the description is yet to update as we discussed in parking lot on that day. Can you please check once.

**Comment by jjeroch** [comment]
@AnuragNagpure  please check if the updated ticket description is enough or needs more information

**Comment by MaximilianHauer** [comment]
@AnuragNagpure  do you need support on this ? did you see @jjeroch  comment ?

**Comment by AnuragNagpure** [comment]
> @AnuragNagpure do you need support on this ? did you see @jjeroch comment ?

no currently understood will do accordingly
