### ISSUE TITLE
GET Document endpoint for Operator running on error

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#556]
Detected in version: **1.8.0**

**Endpoint:** `https://portal-backend.int.demo.catena-x.net/api/administration/documents/80acf14d-69dc-4b92-bb10-c926f7df02bf`

Executed with the operator login on `INT`

Receiving an error - please validate why the issue appears. Start to reproduce it on INT

**Comment by jjeroch** [comment]
Note - almost all documents running on error: 
<img width="317" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/94133633/60a181e0-4e01-4164-8f25-79903e2340e1">
maybe we are using the wrong endpoint

**Comment by AnuragNagpure** [comment]
@jjeroch we are getting this error due one validation check of IsUserInCompany where we can access only those documents which are associated with our company.

**Comment by jjeroch** [comment]
@AnuragNagpure thanks for checking. I had a look at the document endpoints - you are right the endpoint is not usable for the needed scenario. We need to switch.
While checking through all document endpoints I saw that we need a new endpoint for the credentialProof documents.
Since this function is getting moved into the new issuer component - I suggest we close the ticket with "wont do" and I am adding a new scope ticket for the issuer component

**Comment by jjeroch** [comment]
Ticket for issuer component created: https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/27
