### ISSUE TITLE
API GET Technical User(s) - filter on "isOwner" does not work as expected

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#563]
Detected in Version: **dev (not release candidate)**

In the current dev version, the endpoint
`/api/administration/serviceaccount/owncompany/serviceaccounts?size=10&page=0&isOwner=true`
(tested with CX Operator Login)
response with Managed Technical users; instead of only showing the once where the serviceAccountType is `"MANAGED"`

To be checked!

**Comment by jjeroch** [comment]
@VPrasannaK94  & @ntruchsess 
I analyzed the situation based on the proposed pr fix once again.
The issue is not the filter itself; the issue appears on a much earlier state already. Its inside the technicalUserAccount creation.
When looking into the view portal.company_linked_service_accounts saw a number of accounts where following situation exists:
Owner ID and Provider ID is the same - still the technicalUserAccount is under the type "Managed".
I further validated the scenario and realized that this happens whenever a company subscribes to their own service/app offer.
To fix this we need to do the following:
- update technical user account creation backend logic of the following endpoints:
   - POST /api/apps/start-autoSetup
   - POST /api/services/start-autoSetup
in both the endpoints a technical user gets created if a technical user profile exists. This technical user account is always created as "MANAGED".  We need to enhance the logic to only create the technical user as "MANAGED" if the offer provider and subscription customer are not from the same company. Note: in 98% this will be the case; but I also like to have a clean solution for this other 2 percent.
If offer provider and subscription customer company ID is identical, the technicalUserAccount type should be "OWN".

As soon as this is done we need additionally a data fix script which runs with the migration/as part of the deployment.
Set all technicalUserAccount types to "OWN" where offer provider and subscription customer have the same companyID set.

**Comment by jjeroch** [comment]
After discussion with @VPrasannaK94  & @ntruchsess suggestion is to implement the logic via the field "isOwner" of the GET endpoint - by enhancing the "isOwner" attribute logic with the following logic:
- if the portal.company_linked_service_accounts field provider is empty the "isOwner" flag is set to "true
- if the portal.company_linked_service_accounts field provider is filled, following needs to happen: 
  - if "provider" == "owner" set the "isOwner" flag to "true
  - otherwise "isOwner" flag to "false"

**Comment by VPrasannaK94** [comment]
After discussion with @ntruchsess suggestion is to add one more field "isProvider" of the Get endpoint

- if the portal.company_linked_service_accounts field provider is equal to the user companyId then set isProvider flag to "true"
- if the portal.company_linked_service_accounts field owner is equal to the user companyId then set isOwner flag to "true"
