### ISSUE TITLE
Add App Roles (Active app) not providing expected response

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#573]
While adding roles to an active apps via the API call `POST:/api/apps/AppChange/${appId}/role/activeapp`
the api response returns "success" 

However if we now call the appRoles with 
`GET: /api/administration/user/owncompany/roles/apps/${appId}`
the response is empty

```json
[]
```

Check needed.
Tests executed on `dev`
Example app ID: `a376f2c7-c5c9-46f6-96c8-4bafee3c2183`

Please note: while analysing and fixing the issue; we should consider to move this endpoint to the app controller since this is connected to "apps". As soon as analysis of the issue is done; we should quickly align on the move of the endpoint

---

After analysing the ticket with Prasanna the following decision was made:
For the app provider an endpoint is needed to fetch the roles of an active app.
Till now we used an endpoint from administration service; but to ensure that we have a clear differenciation of the endpoints and services, we decided to create a own endpoint inside the app services.

**Endpoint**: `/api/apps/{appId}/roles`
**Method**: `GET``

Optional parameter: languagetag

**Response Body**
```json
[
  {
    "role": "string",
    "descriptions": [
      {
        "languageCode": "string",
        "description": "string"
      }
    ]
  }
]
```

Validation: only active apps should be callable.

The endpoint provides requesters an overview of available app roles of active apps.

**Comment by lavanya-bmw** [comment]
While adding roles to the active apps, if the api response for GET: /api/administration/user/owncompany/roles/apps/${appId}` is [] and tried to add additional roles via POST: `/api/apps/AppChange/${appId}/role/activeapp`, the post gets successful. Now, when GET api is called again, there should be roles available, but instead GET call responds with empty([]).

**Comment by VPrasannaK94** [comment]
As discussed with @jjeroch created an endpoint GET: /api/apps/AppChange/{appId}/roles to fetch the active app userRoles details.

**Comment by VPrasannaK94** [comment]
SucessFully Tested in dev
