### ISSUE TITLE
IDP List endpoint returns HTTP 500 Internal Server Error  

### ISSUE THREAD

**Issue by oyo** [eclipse-tractusx/portal-backend#584]
### Current Behavior

In the dev environment the IDP list endpoint
https://portal-backend.dev.demo.catena-x.net/api/administration/identityprovider/owncompany/identityproviders
returns an error for IDP+user

CX-Operator
cx-operator@cx.com

```
{
    "type": "https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.1",
    "title": "The server encountered an unexpected condition.",
    "status": 500,
    "errors": {
        "Org.Eclipse.TractusX.Portal.Backend.Provisioning.Library": [
            "client_id of identityProvider is null"
        ]
    },
    "errorId": "39d198ce-73e4-4e57-ae5e-779d43c18a3a",
    "details": []
}
```

### Expected Behavior

We expect a HTTP 200 result containing an array of IDP entries

### Steps To Reproduce

- open portal https://portal.dev.demo.catena-x.net/idpmanagement
- login with CX-Operator user
- if not already done open developer tools network tab and reload
- check the endpoint with path suffix "identityproviders"
- notice the 500 error in the request response

**Comment by Phil91** [comment]
This issue seems to be fixed with #682 - tested on the rc environment. will test again after we did the next release
