### ISSUE TITLE
Missing Unique Identifier in GET /api/administration/registration/application/{applicationId}/companyDetailsWithAddress Endpoint

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#606]
Detected in version: *1.7.0*

**Description:**
With the recent pull request (PR) [link](https://github.com/eclipse-tractusx/portal-backend/pull/329), an issue has been introduced in the `GET /api/administration/registration/application/{applicationId}/companyDetailsWithAddress` endpoint. The unique identifiers are no longer being provided in the response, causing a loss of critical information. This ticket aims to address and fix this issue promptly.

**Steps to Reproduce:**
1. Make a GET request to the `/api/administration/registration/application/{applicationId}/companyDetailsWithAddress` endpoint.
2. Inspect the response received.

**Expected Behavior:**
The response should include the unique identifiers associated with the company details and address for the specified application ID.

**Actual Behavior:**
The unique identifiers are missing from the response, making it difficult to identify and differentiate the company details and addresses.

**Bug Details:**
- Endpoint: GET /api/administration/registration/application/{applicationId}/companyDetailsWithAddress
- PR which likely introduced the issue: [link](https://github.com/eclipse-tractusx/portal-backend/pull/329)

**Comment by drhansbeck** [comment]
I take it 💪 thanks for creating the issue @jjeroch !

**Comment by drhansbeck** [comment]
#612 which fixes this issue was merged. Closing this issue. Thanks to everyone involved. Love to see the collaboration between teams 👏👏
