### ISSUE TITLE
Missing BPDM Identifier Type in BpdmIdentifierId and Database

### ISSUE THREAD

**Issue by typecastcloud** [eclipse-tractusx/portal-backend#618]
Detected in version: v1.7.0, v1.8.0, main, dev

### Description:
DUNS_ID not supported by portal backend. Exists in [Tractus-X BPDM reference implementation](https://github.com/eclipse-tractusx/bpdm/blob/main/bpdm-pool/src/main/resources/db/migration/V2_0_2_2__insert_country_identifier_types.sql).

For both new and old BPDM gate endpoint calls:
/api/catena/output/legal-entities/search
/api/catena/output/business-partners/search

Whenever there is a legal entity with DUNS_ID as type, there is a JsonException in portal backend.

### Current Behavior
JsonException with ERROR message when receiving a reply with DUNS_ID as one of the identifiers.

"Access to external system bpdm did not return a valid json response: The JSON value could not be converted to Org.Eclipse.TractusX.Portal.Backend.Bpdm.Library.Models.BpdmIdentifier. Path: $.content[0].identifiers[1].type | LineNumber: 0 | BytePositionInLine: ***."

### Expected Behavior
Properly convert the JSON object into a BpdmIdentifier with DUNS_ID.

### Steps To Reproduce
Use the FetchInputLegalEntity function for a legal entity that returns DUNS_ID or run FetchInputLegalEntity_WithValidResult_ReturnsExpected with a JSON that contains DUNS_ID as a type (test fails).

@jjeroch first issue created by me. Please tell me if there are more details needed.
@ntruchsess I am fixed this issue in my fork of tractus-x dev branch. For a database migration I need support. I'll create a PR.

**Comment by ntruchsess** [comment]
@jjeroch as this issue and it's solution is pretty straightforward I did create new PR #624 based on @typecastcloud PR #619 adding the missing migration and adjusting the unit-tests adding further asserts. From my point of view this is ready to merge.

**Comment by ntruchsess** [comment]
@jjeroch : an alternative to add new types to BpdmIdentifierId just to be able to parse the bpdm-response would be to ignore those values entirely by mapping to string instead of the enum-type.
As in the response only the bpnl is being used it wouldn't make a  difference.

**Comment by ntruchsess** [comment]
#657 is merged, the bpdm-identifier-type is now mapped to string in json-deserialization (and as it is not being used in code any unknown values are just ignored)
