### ISSUE TITLE
Failing POST /api/registration/application/{applicationId}/companyDetailsWithAddress -  BPN Error 

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#639]
Detected in version **2.0.0 RC1**

Bug Description: POST /api/registration/application/{applicationId}/companyDetailsWithAddress fails when a payload without BPNL (Business Partner Number List) is provided.

<img width="1276" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/94133633/3da1aa7a-78a7-4db1-bffb-37ed1ee75281">

Steps to Reproduce:
1. Send a POST request to /api/registration/application/{applicationId}/companyDetailsWithAddress endpoint.
2. Provide a payload without BPNL in the request body.
3. Submit the request.

Expected Result:
The request should be processed successfully, and the company details with address should be saved in the backend (db)

Actual Result:
The request fails with an error message.

Error Message:
"Invalid payload. BPNL (Business Partner Number List) is missing."

Additional Information:
- The BPNL field can be
  - empty
  - or filled (in this case it must be 16digits long)
- The BPNL should be included in the payload sent to the /api/registration/application/{applicationId}/companyDetailsWithAddress endpoint.
- The BPNL should be validated before processing the request.

Impact:
- Users are unable to complete the registration process if they do not provide the BPNL.

**Comment by evegufy** [comment]
> @jjeroch I tested it with the following request:
> 
> ```json
> {
>   "name": "Test Company",
>   "city": "Munich",
>   "streetName": "Street",
>   "countryAlpha2Code": "DE",
>   "shortName": "Test",
>   "region": "BY",
>   "zipCode": "00001",
>   "uniqueIds": [
>     {
>       "type": "VAT_ID",
>       "value": "DE123456789"
>     }
>   ],
>   "companyId": "ac861325-bc54-4583-bcdc-9e9f2a38ff84"
> }
> ```
> 
> and it was working successfully. Can you maybe provide the request which resulted in the error?

@Phil91 I'll ping you

cc: @jjeroch

**Comment by evegufy** [comment]
tested successfully. Thanks @Phil91
