### ISSUE TITLE
InviteNewUser during Registration | No mail sent

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal-backend#645]
### Current Behavior

When inviting an additional user in the second set of the registration, no mail notification is sent to the new user

### Expected Behavior

Mail notification is sent to the new user

![image](https://github.com/eclipse-tractusx/portal-backend/assets/46191613/3aab571c-f857-4fbc-b58d-488c25df2619)

### Additional information

Detected in version 2.0.0-RC1

The provisioning aka user creation in centralidp and sharedidp works just no mail is sent to the new user

**Comment by Phil91** [comment]
@evegufy I will take care of the issue, did an onboarding to test some things on rc and already found the issue. PR will be created soon.

**Comment by Phil91** [comment]
@evegufy  tested on rc.
/cc @jjeroch

**Comment by evegufy** [comment]
successfully retested, thanks @Phil91
