### ISSUE TITLE
Aggregate release branch rc3 migrations to 2.0.0-rc3

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal-backend#659]
### Description

The aggregation of the current migrations within the dev branch to a '2.0.0-rc3' migration is needed in preparation for https://github.com/eclipse-tractusx/portal/issues/264

**Comment by Phil91** [comment]
the following script needs to be executed on the rc database after the merge:

```sql
update public.__efmigrations_history_portal
set migration_id = '20240423033553_2.0.0-rc3'
where migration_id = '20240418104402_593-AddNewDimProcess';
```
