### ISSUE TITLE
Registration Service - Update BPDM Search Endpoint

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#661]
**Summary:**
The current implementation of the BPDM search endpoint, which is wrapped behind the portal endpoint `GET /api/registration/legalEntityAddress/{bpn}`, needs to be updated. The new implementation should switch to the endpoint `POST /v6/members/legal-entities/search`, with the BPNL (Business Partner Number List) included in the request body.

**Details:**
- Current Endpoint: GET /api/registration/legalEntityAddress/{bpn}
- New Endpoint: POST /v6/members/legal-entities/search
- Swagger Documentation: [Legal Entity Controller - searchLegalEntities](https://business-partners.int.demo.catena-x.net/pool/ui/swagger-ui/index.html#/Legal%20Entity%20Controller/searchLegalEntities)

**Steps:**
1. Update the endpoint from `GET /api/registration/legalEntityAddress/{bpn}` to `POST /v6/members/legal-entities/search`.
2. Include the BPNL (Business Partner Number List) in the request body...make sure that this does not have an impact on the FE.
3. Ensure that the request follows the specifications provided in the Swagger documentation for the `searchLegalEntities` endpoint.
4. Test the updated endpoint thoroughly to ensure its functionality and compatibility with the existing system. (contact BPDM if tests locally are not supported)
5. Update any relevant documentation or references to reflect the changes made. (inside assets - @jjeroch  can help - but we need to ensure that we update the docu)

**Expected Outcome:**
After implementing this change, the BPDM search endpoint will be switched to the new endpoint `POST /v6/members/legal-entities/search` this will allow users with the limited BPDM access rights to fetch company data (to be tested)

**Comment by jjeroch** [comment]
@Phil91 could you please have a look at this ticket and check if anything is still needed here?

**Comment by Phil91** [comment]
> @Phil91 could you please have a look at this ticket and check if anything is still needed here?

will directly do

**Comment by Phil91** [comment]
@jjeroch double checked on int. working fine.
