### ISSUE TITLE
Create Identity Provider endpoint fails | expects client_id

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal-backend#682]
### Current Behavior

The endpoint for creating an Identity Provider fails because it expects a client_id:

/api/administration/identityprovider/owncompany/identityproviders

´´´
{
    "type": "https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.1",
    "title": "The server encountered an unexpected condition.",
    "status": 500,
    "errors": {
        "Org.Eclipse.TractusX.Portal.Backend.Provisioning.Library": [
            "client_id of identityProvider is null"
        ]
    },
    "errorId": "e8c96d81-4cfd-4ff6-8038-6893bd4d9a46",
    "details": []
}
´´´

### Expected Behavior

Endpoint creates the IdP.

### Steps To Reproduce

Detected in **v2.0.0-RC4**

**Comment by ntruchsess** [comment]
if this referring to the POST endpoint then this endpoint is not 'expecting' a client_id. After creation of the new idp it tries to read the identity-provider-config from keycloak to return it's details to the FE. In case the client_id of this newley created idp is not included in the keycloak api response (this is apparently what happened here) it results in the given error.
(this is just explaining the detailed cause of the error-message, I'll investigate what might have gone wrong before).

**Comment by jjeroch** [comment]
@ntruchsess both endpoints
GET /api/administration/identityprovider/owncompany/identityproviders
&
POST /api/administration/identityprovider/owncompany/identityproviders
running on error.

Env.INT
User: CX Operator

**Comment by evegufy** [comment]
Fix is successfully tested
