### ISSUE TITLE
Refactor Attributes in GET /api/administration/companydata/decentralidentity/urls Endpoint

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#683]
`Follow up ticket of #674 & #643 `

In addition to the current implemented values provided via the backend API Call GET companyData/decentralidentity/urls
we need to add the following values:

```json
  "trusted_issuer":"{didWebOperator}", //single value only, in future where multiple exists, we wont provide the info like that
  "participant_id":"{usersCompanyBPNL}",
  "iatp_id":"{did:web of the holder}",
  "did_resolver":"{did resolver url - https://bpn-did-resolution-service.int.demo.catena-x.net/api/directory/}"
```

**Comment by Phil91** [comment]
@jjeroch I think we need to discuss the did_resolver path... at the moment the did resolver is only accessible from inside argo. meaning everybody else won't be able to reach it.

**Comment by Phil91** [comment]
> [@jjeroch](https://github.com/jjeroch) I think we need to discuss the did_resolver path... at the moment the did resolver is only accessible from inside argo. meaning everybody else won't be able to reach it.

Discussion did take place, since the bpn did resolver is now public available, there's no problem anymore
