### ISSUE TITLE
Enhance GET /api/administration/registration/application/{applicationId}/companyDetailsWithAddress endpoint

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#685]
### Summary
Enhance the GET /api/administration/registration/application/{applicationId}/companyDetailsWithAddress endpoint to include the "document" section in the response body. The logic for adding the "document" section should be the same as the one used for the `GET /api/administration/registration/applications` endpoint.

Additionally include the "created" and "lastChanges" dates from the portal table "company_applications" in the response body of the GET /api/administration/registration/application/{applicationId}/companyDetailsWithAddress endpoint.

Once the above changes are implemented, remove the "document" section from the response body of the GET /api/administration/registration/applicationsWithStatus endpoint.

**Acceptance Criteria:**
- The GET /api/administration/registration/application/{applicationId}/companyDetailsWithAddress endpoint should include the "document" section in the response body.
- The logic for adding the "document" section should be the same as the one used for the GET /api/administration/registration/applications endpoint.
- The "created" and "lastChanges" dates from the portal table "company_applications" should be included in the response body of the GET /api/administration/registration/application/{applicationId}/companyDetailsWithAddress endpoint.
- The "document" section should be removed from the response body of the GET /api/administration/registration/applications endpoint.

**Comment by ntruchsess** [comment]
@jjeroch GET /api/administration/registration/applications doesn't return any document details and therefore doesn't have any document-selection?
