### ISSUE TITLE
R24.05 | improve code quality

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal-backend#694]
### Description

Solve the following issues:

- [x] Enable server certificate validation on this SSL/TLS connection

https://github.com/eclipse-tractusx/portal-backend/security/code-scanning/1476

- [ ] 'identityProviderLinks' is null on at least one execution path

https://sonarcloud.io/project/issues?impactSeverities=MEDIUM&impactSoftwareQualities=RELIABILITY&resolved=false&id=eclipse-tractusx_portal-backend&open=AY6pS-zDDZB9YaX0ezSq

- [x] Logging arguments should be passed to the correct parameter (2 cases). - fixed in [#715](https://github.com/eclipse-tractusx/portal-backend/pull/715)

https://sonarcloud.io/project/issues?impactSeverities=MEDIUM&impactSoftwareQualities=RELIABILITY&resolved=false&id=eclipse-tractusx_portal-backend&open=AY6pS-QtDZB9YaX0ezSO

https://sonarcloud.io/project/issues?impactSeverities=MEDIUM&impactSoftwareQualities=RELIABILITY&resolved=false&id=eclipse-tractusx_portal-backend&open=AY6pS_DODZB9YaX0ezTH

- [x] Specify the RouteAttribute when an HttpMethodAttribute or RouteAttribute is specified at an action level (22 cases)
https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&impactSeverities=HIGH&id=eclipse-tractusx_portal-backend

### Additional information

detected in v2.0.0-RC5

**Comment by Phil91** [comment]
@evegufy in my opinion the remaining open finding 'identityProviderLinks' is null on at least one execution path is a false positive, but would like to check that with norbert

**Comment by jjeroch** [comment]
unassigned from phil; Norbert will have a look at the last open ticket
