### ISSUE TITLE
Invite Service - Delay in displaying application record after company invite

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#700]
**Summary:**
Currently, there is a delay in displaying the application record to the admin after inviting a new company. This delay is caused by the process worker, which prevents the admin from immediately seeing the triggered invite. As a result, the admin might mistakenly assume that the invite was unsuccessful. 

To improve this behavior, we need to implement a solution that allows the triggered invite to be displayed in real time via the `GET /api/administration/registration/applicationsWithStatus?page=0&size=10&companyName=` endpoint. This will provide the admin with immediate visibility of the application record after the company invite.

**Steps to Reproduce:**
1. Invite a new company POST /api/administration/invitation
2. Check the `GET /api/administration/registration/applicationsWithStatus?page=0&size=10&companyName=` endpoint
3. Observe the delay in displaying the application record

**Expected Result:** The application record should be displayed immediately after the company invite.

**Actual Result:** There is a delay in displaying the application record, causing confusion for the admin.

**Proposed Solution:**
1. Implement real-time updates for the `GET /api/administration/registration/applicationsWithStatus?page=0&size=10&companyName=` endpoint.
2. Update the endpoint to display the triggered invite as soon as it is available.

**Comment by MaximilianHauer** [comment]
@Phil91  topic is solved with your pr i assume ? assigned it to you

**Comment by Phil91** [comment]
> @Phil91 topic is solved with your pr i assume ? assigned it to you

Correct, as soon as the PR is merged the company and application can be displayed directly
