### ISSUE TITLE
Release & Test Seeding Data Adjustments

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#702]
### Seeding data update needed

**Release Seeding Data**

- Add new document inside the file `/portalbackend/PortalBackend.Migrations/Seeder/Data/documents.json`
```
  {
    "id": "//to be generated by the developer",
    "date_created": "2024-01-01T19:29:08.602237+00:00",
    "document_name": "SelfDescription_LegalPerson.json",
    "media_type_id": 7,
    "document_type_id": 8,
    "company_user_id": null,
    "document_hash": "//to be generated by the developer",
    "document_content": "//to be generated by the developer",
    "document_status_id": 2,
    "last_editor_id": "7e85a0b8-0001-ab67-10d1-0ef508201027"
  }
```

- Update the company record inside the `/PortalBackend.Migrations/Seeder/Data/companies.json` file for the CX Operator
```
"self_description_document_id": "{uuid of the document record loaded above}"
```

---

In `portal.user_role_assigned_collections` assign

- BPDM Sharing Input Consumer
- BPDM Sharing Output Consumer

to the collection of the `app provider` and `service provider`

**Comment by Phil91** [comment]
@jjeroch how should the file look like? Currently the following file is uploaded, that doesn't seems right.

[x.pdf](https://github.com/eclipse-tractusx/portal-backend/files/15224411/x.pdf)
