### ISSUE TITLE
Empty audit table for company user assigned role changes

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#720]
**Description:**
The existing audit table `portal.audit_company_user_assigned_role` is not capturing any records when adding or deleting company user assigned roles. This is a critical issue as it hinders the ability to track and audit changes made to company user roles, which is an important requirement for compliance and security purposes.

**Steps to Reproduce:**
1. Add a new company user assigned role.
2. Delete an existing company user assigned role.
3. Check the `portal.audit_company_user_assigned_role` table for any records.

**Expected Behavior:**
When adding or deleting company user assigned roles, the audit table `portal.audit_company_user_assigned_role` should capture the relevant information, including the user, role, timestamp, and action performed. This allows for proper auditing and tracking of changes made to company user roles.

**Actual Behavior:**
The audit table `portal.audit_company_user_assigned_role` is empty and does not contain any records related to company user assigned role changes.

**Tasks:**
Debug and fix the issue to ensure that the expected behavior is reached.

**Comment by AnuragNagpure** [comment]
Hi @jjeroch there is already portal.audit_identity_assigned_role which captures add delete and other operation. portal.audit_company_user_assigned_role is currently empty and not associated with any task

**Comment by jjeroch** [comment]
@AnuragNagpure any status update?

**Comment by AnuragNagpure** [comment]
> @AnuragNagpure any status update? If you successfully tested the function with the existing table, please update the ticket to "in Review"

Sure

**Comment by MaximilianHauer** [comment]
@AnuragNagpure the table seems to be empty please can you have a look ?

**Comment by MaximilianHauer** [comment]
as aligned old tables can be removed to reduce confusion as long as they are empty.

**Comment by MaximilianHauer** [comment]
portal.audit_identity_assigned_role works
