### ISSUE TITLE
Error when trying to confirm a declined registration request as an administrator

### ISSUE THREAD

**Issue by danakoch23** [eclipse-tractusx/portal-backend#723]
# Defect Ticket

**Problem:** Error when trying to confirm a declined registration request as an administrator
**Error message:** 
```
"type": "https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.1",
"title": "The server encountered an unexpected condition.",
"status": 500,
"errors": {
    "Org.Eclipse.TractusX.Portal.Backend.Provisioning.Library": [
        "clientId saidp70 not found on shared idp"
    ]
},
"errorId": "8b32fdc6-8d62-482d-ad39-15cf92ceeb36",
"details": []
```

## Problem Description
When attempting to confirm a declined registration request as an administrator, an error occurs. Clicking on "Confirm" results in the error message "The server encountered an unexpected condition." with a status code of 500. Additionally, the error object "errors" returns the error message "clientId saidp70 not found on shared idp" associated with the `errorId` "8b32fdc6-8d62-482d-ad39-15cf92ceeb36".

## Steps to Reproduce
1. Log in as an administrator
2. Go to the Application Request (Admin Board)
3. Select a company and go on Data Validation.
4. Click on "Decline"
5. Click on "Confirm"
6. Receive the error message "The server encountered an unexpected condition." with a status code of 500
7. Find the error message "clientId saidp70 not found on shared idp" in the "errors" error object

## Expected Behavior
Confirming a declined registration request should be possible without any errors. There should be no error message stating "The server encountered an unexpected condition." with a status code of 500. Additionally, the error message "clientId saidp70 not found on shared idp" should not be present in the "errors" error object.

**Comment by Phil91** [comment]
in my opinion the problem is the same as in #724
