### ISSUE TITLE
Trace-X B App subscription stucks for several days

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/portal-backend#736]
### Current Behavior
Trace-X B is stuck in "Setup Ongoing" state for the past two days. Upon attempting to subscribe to the app from Trace-X A again, an HTTP Error 409 (Conflict) is encountered.

### Expected Behavior
After correcting the Tenant URL issue and re-subscribing to the app from Trace-X A, the subscription process should be successful without encountering any errors.

### Steps To Reproduce
1. Trace-X A: Create app and self-subscribe.
2. Trace-X B: Subscribe to app from Trace-X A (successful), but with incorrect Tenant URL.
3. Trace-X B: Unsubscribe from the app.
4. Trace-X B: Attempt to re-subscribe to the app from Trace-X A with corrected Tenant URL.
5. Encounter HTTP Error 409 (Conflict).

Additional details:
- Trace-X B has been stuck in "Setup Ongoing" state for two days.
- Environment: INT 

![image](https://github.com/eclipse-tractusx/portal-frontend/assets/100209308/5fda1749-1af8-43cd-9e6e-2128a14608f8)

![SubscriptionStucks](https://github.com/eclipse-tractusx/portal-frontend/assets/100209308/4314edec-1583-4d2d-9bd9-253b1a3dd88b)

**Comment by jjeroch** [comment]
Validated and issue found with a company setting (service integration data configured by an user via the self-service). Disussed with the issue author any fixed. No code adjustments needed
