### ISSUE TITLE
Role Assignment Triggering Cascading Assignments

### ISSUE THREAD

**Issue by tfjcofinity** [eclipse-tractusx/portal-backend#748]
We are facing an issue related to the role assignments of a user in the _Portal User Management -> Details of a user_ screen after merging v1.8.0 (release 24.03). The issue has been explained in the attached video, please find it from the attachment.

### Current Behavior
Currently, when we try to update roles of a user e.g: “App Manager“ so, other roles e.g: “Company Admin“, "CX Admin", "CX User" roles are automatically assigning. (Please check the attached video)

https://github.com/eclipse-tractusx/portal-backend/assets/158485550/d98c69d8-c21a-4d71-aff3-dfcb99c89cc8

### Expected Behavior
Users should only be assigned the selected roles.

### Steps To Reproduce

- Login to the portal application as CX-Operator user
- Update any user’s role from _Portal User Management -> Details of a user_ screen.
- Update and assign different role and you will see that user would get assigned different roles than the selection.

Login with CX-Operator user and try to update any other user's role.
This issue can be see in Release 24.03 
The issue has been explained in the attached video, please find it from the attachment.

**Comment by jjeroch** [comment]
Issue was likely introduced by following PR: https://github.com/eclipse-tractusx/portal-backend/pull/321/files#diff-8a62ebca806de7cc9faec2e04041b0e3b2c0115ce34144e79f7a66ffdc7af17f

---

http method:  PUT
 
url: /api/administration/user/owncompany/users/{companyUserId}/coreoffers/{offerId}/roles
 
payload: [ "App Manager" ]

---

**Hints from Code**:
UserController.cs -> ModifyCoreUserRolesAsync
UserRolesBusinessLogic.cs -> ModifyCoreOfferUserRolesAsync -> ModifyUserRolesInternal

**Comment by jjeroch** [comment]
Additional Info: More roles as expected are getting assigned to the user. The issue must lay in the backend logic.
We are looking into it now.

Positive fact: Keycloak and portal backend are in sync.

**Comment by typecastcloud** [comment]
Thank you for the quick fix @ntruchsess.
