### ISSUE TITLE
TRG 7.02 - License and copyright header 

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/portal-backend#752]
Please correct license header referring to Catena-X org

https://github.com/eclipse-tractusx/portal-backend/blob/v2.0.0-RC7/src/administration/Administration.Service/Models/CompanyWithAddressData.cs

cc: @evegufy , @fabiodmota 

updates: https://github.com/eclipse-tractusx/portal-backend/issues/733

**Comment by evegufy** [comment]
@tomaszbarwicki thanks for spotting that, it corrected now https://github.com/eclipse-tractusx/portal-backend/blob/v2.0.0-RC9/src/administration/Administration.Service/Models/CompanyWithAddressData.cs
