### ISSUE TITLE
Process Worker "send email" limited information to verify details

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#763]
**Env** `INT`
**Version**: 2.0.0 RC9

Send Email Process Steps created without reference for what the email got actually send.
How can users/admins, etc. verify the details best?

<img width="1367" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/94133633/772950d3-db93-4d91-92fb-3894f457fc68">

**Comment by Phil91** [comment]
@jjeroch I'd recommend a query like this:

```C#
select MI.email, MI.template, P.message from portal.mailing_informations as MI JOIN portal.process_steps as P ON MI.process_id = P.process_id
```

if we want to have the information of the template in the message I could add that as well.

**Comment by jjeroch** [comment]
> @jjeroch I'd recommend a query like this:
> 
> ```cs
> select MI.email, MI.template, P.message from portal.mailing_informations as MI JOIN portal.process_steps as P ON MI.process_id = P.process_id
> ```
> 
> if we want to have the information of the template in the message I could add that as well.

@Phil91  I think we need a further enhancement of the SQL. With that I still cant connect it to the processFlow itself.
Maybe to specify the requirement from my side might be helpful:

- i want to make sure that the operation team can identify for "sendEmail" process steps which email was send to which user
- the operation team needs to be aware at which time this email was send
- the operation team needs to be able to check for unsuccessful cases to which user for which scenario the send_email job failed

**Comment by Phil91** [comment]
> > @jjeroch I'd recommend a query like this:
> > ```cs
> > select MI.email, MI.template, P.message from portal.mailing_informations as MI JOIN portal.process_steps as P ON MI.process_id = P.process_id
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > if we want to have the information of the template in the message I could add that as well.
> 
> @Phil91 I think we need a further enhancement of the SQL. With that I still cant connect it to the processFlow itself. Maybe to specify the requirement from my side might be helpful:
> 
> * i want to make sure that the operation team can identify for "sendEmail" process steps which email was send to which user
> * the operation team needs to be aware at which time this email was send
> * the operation team needs to be able to check for unsuccessful cases to which user for which scenario the send_email job failed

@jjeroch I have adjusted the sql, it should now meet all requirements :)

```sql
SELECT MI.email, MI.template, P.date_created, PSS.label, P.message 
FROM portal.mailing_informations AS MI 
JOIN portal.process_steps AS P ON MI.process_id = P.process_id
JOIN portal.process_step_statuses AS PSS ON P.process_step_status_id = PSS.id
```
