### ISSUE TITLE
When trying to register a partner in the created IDP and filling in all the required data, an error occurs with the following details:

### ISSUE THREAD

**Issue by danakoch23** [eclipse-tractusx/portal-backend#767]
Defect

 TEST-1762, TEST-1763, TEST-1764

**Summary:** Error occurs when trying to register a partner in the created IDP

**Description:**
When trying to register a partner in the created IDP and filling in all the required data, an error occurs with the following details:

**Request URL:**
https://portal-backend.int.demo.catena-x.net/api/administration/registration/Network/partnerRegistration

**Error Response:**
```json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "errors": {
        "UniqueIds": [
            "invalid uniqueIds for country DE: '0' (Parameter 'UniqueIds')"
        ]
    }
}
```

**Reproduction Steps:**
1. Navigate to the partner registration page in the IDP
2. Click on Details and then Register Partner
3. Fill in all the required data for a new partner
4. Attempt to submit the registration form
5. Observe the error message indicating an issue with the "UniqueIds" parameter

**Expected Behavior:**
The partner registration should be successful without any errors.

**Actual Behavior:**
The partner registration fails with an error message indicating an issue with the "UniqueIds" parameter.

**Comment by jjeroch** [comment]
Frontend Issue - Defect created: https://github.com/eclipse-tractusx/portal-frontend/issues/826
This ticket is getting closed
