### ISSUE TITLE
sig#796: SST Clearinghouse - Implement Feature Toggle for Clearinghouse Self-Description Connectivity

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#792]
### Description

We require an enhancement to the current implementation of the clearinghouse connection within the `portal-backend` project. The goal is to introduce a feature toggle that allows disabling the connection to the clearinghouse for Self-Description (SD) functions. This should affect both Legal Person and Participant Self-Descriptions. When the toggle is set to disable the connectivity, the system should still be able to complete the application process and connector registration without establishing a connection to the clearinghouse.

### Acceptance Criteria

1. **Feature Toggle Implementation:**
   - Introduce a feature toggle (e.g., `CLEARINGHOUSE_CONNECT_DISABLED`) that can be switched on or off to enable or disable the clearinghouse SD connectivity.
   - The toggle does not need to be accessible and changeable at runtime, I would actually suggest a system restart need instead. Reason: we should not switch easily around.

2. **Application Process Handling:**
   - Ensure that with the toggle is set to true (clearinghouseConnect is disabled), the application process for Legal Person and Participant can be completed successfully without any clearinghouse connectivity.
   - Ensure that with the toggle set to true (clearinghouseConnect is disabled), the connector registration and connector change flow can be completed successfully without any clearinghouse connectivity.
     - The status of the connector is set to pending
   - Ensure that with the toggle is set to false (clearinghouseConnect is enabled), the process stays as it is and the call to Legal Person and Participant calls are made.
   - Ensure that with the toggle set to false (clearinghouseConnect is enabled), the connector registration and connector change flow stays as it is and the connector is registered with a sd factory is made.
     - The status of the connector is set to pending

3. **Runtime Activation Handling:**
   - SD Factory/Clearinghouse Application: In case the toggle is active, set the respective process status to "skipped"
   - Connector: In case the toggle is active, with a creation of a connector registration by the customer the status is immediately set to active

~~4. **User Interface Notification:**~~
 ~~- Propose a method to inform users via the UI about the status of the clearinghouse SD connectivity, especially if it impacts  their current state.~~
~~- This UI information should be clear and informative, providing users with an understanding of the implications of the SD connectivity status.~~

5. **Validation Scenarios:**
   - Define and document specific scenarios to validate the behavior of the system with the toggle switched on and off.

6. **Documentation:**
   - Update the project documentation to include the new feature toggle and its implications on the system's operation.

7. **Error Handling and Logging:**
   - Ensure that relevant logs are generated for monitoring and debugging purposes. `//Note: I expect this to be in place, this is just to recheck`

### Implementation Notes

- The feature toggle should be implemented in a way that it can be easily accessed and modified by system administrators (under the above defined processes).
- The system's behavior when the toggle is switched needs to get thoroughly tested to prevent any unexpected issues.

**Comment by jjeroch** [comment]
Bug found: https://github.com/eclipse-tractusx/portal-backend/issues/887

**Comment by MaximilianHauer** [comment]
tested and approved
