### ISSUE TITLE
IF BPDM Sharing company data (Registration process)

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#801]
### Summary
Interface BPDM - Portal to be checked; receiving a new error message which leads to the feeling that BPDM had a breaking change and the interface might be broken.

### Details

Data Set (INT)
applicationID: f9d646bb-a0ae-47b8-9594-858719adbceb

BPDM Response Comment:
ErrorCode: SharingProcessError, ErrorMessage: Alternative Address has no country

Task: to be checked - the company address has a country defined; not sure why the country is now giving an error. BPDM seems to have a breaking change. Alignment with BPDM needed.

- What happened
- in which release did this happen?
- how can we solve it?

**Comment by jjeroch** [comment]
Waiting for BPDM. Issue in the integration flow
@evegufy impact on registration flow for e2e Test - BPDM fix needed.

**Comment by anjuchaurasiya** [comment]
How to pass alternative address ?

Please let us know what information in need to pass in the form to avoid this error bcoz we dont see such field available on the form while registering the user : [TaskErrorDto(type=Unspecified, description=Alternative Address has no country)]

**Comment by evegufy** [comment]
Hi @anjuchaurasiya it's not a portal issue, you need to BPDM Patch version https://github.com/eclipse-tractusx/bpdm/pull/983, [chart version 5.0.3](https://github.com/eclipse-tractusx/bpdm/tree/bpdm-5.0.3)

**Comment by anjuchaurasiya** [comment]
Thank you @evegufy
