### ISSUE TITLE
sig#809: GET Endpoint for Retrieving Onboarded OSP Companies and Their Statuses

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#808]
Description:
We need to develop a new API GET endpoint that will allow users to retrieve a list of all Onboarded OSP (Onboarding Service Provider) companies along with their current status. This endpoint will be used to provide an overview of the companies that are currently using our platform and their operational status.

Acceptance Criteria:
1. The GET endpoint should be accessible at `/api/administration/registration/network/companies`.
2. The endpoint must return a list of companies with each entry containing the company's name, company data, connected IdP, and their onboarding status.
3. Ensure the response is paginated if the number of companies exceeds a certain threshold of 20 records per page
4. Include appropriate sorting and filtering capabilities based on the company's name and status.
5. Implement proper authentication and authorization checks to ensure that only authorized users can access this endpoint.
6. Include unit tests that cover all critical paths of the functionality.
7. Ensure the response format adheres to the JSON:API specification for better consistency and standardization.
8. The API should handle errors gracefully and return the appropriate HTTP status codes.
9. Update the API documentation to reflect the new endpoint and its usage.

Technical Tasks:

```json
{
  "meta": {
    "totalElements": 0,
    "totalPages": 0,
    "page": 0,
    "contentSize": 0
  },
  "content": [
    {
      "companyId": "uuid",
      "applicationId": "uuid",
      "applicationStatus": "CREATED",
      "applicationDateCreated": "2024-06-24T19:43:59.670Z",
      "lastChangedDate": "2024-06-24T19:43:59.670Z",
      "companyName": "string",
      "companyRoles": [
        "ACTIVE_PARTICIPANT"
      ],
      "identityProvider": [
           {
              "id": "uuid",
              "name": "aliasName"
          }
       ],
      "bpn": "string",
      "activeUsers": "{countActiveOrCreatedCompanyUsers}",
    }
  ]
}
```

### Details:

Fetch all companies/application which are invited by the OSP from table portal.company_applications with a company_application_type_id = `2` (EXTERNAL) and where current users company ID = the company ID stored inside portal.company_applications under `onboarding_service_provider_id`

`companyId`: uuid from table companies
`companyName`: `name` from table companies
`applicationId`: uuid from table company_applications 
`applicationStatus`: application status from company_applications.application_status_id (please use the label; not the enum)
`applicationDateCreated`: date available inside company_applications.date_created
`lastChangedDate`: date available inside company_applications.date_last_changed
`companyRoles`: List of selected company roles from table portal.company_assigned_roles
`identityProvider`: uuid and name. `Name` from iam_identity_providers.iam_idp_alias and `uuid` from company_identity_providers.identity_provider_id
`bpn`: can be null. provides the data stored inside table companies.business_partner_number
`activeUser`: count the company assigned company_users from table portal.company_users and count all users assigned to the company except those which are DELETED inside the identities.user_status_id

----

### Enable Search by Company Name
- minimum 3 characters
- maximum 180 characters
- can contain
  - any A-Z alphabetical characters (including characters with accents or other diacritical marks)
  - & (ampersand)
  - @ (‘at’ symbol)
  - £ (pound sterling sign)
  - $ (dollar sign)
  - € (euro sign)
  - ¥ (yen sign)
  - Numerical digits – 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
  - full stops, commas, colons, semi-colons, and hyphens
  - other punctuation, including apostrophes, brackets, exclamation marks, guillemet, inverted commas, question marks, and solidus
- signs and symbols not used as one of the first three characters in the company name. These are:
  - *(asterisk)
  - =(equals sign)
  - +(plus sign)
  - #(hashtag)
  - % (percent sign)
  -  (space)

#### Test Values

`success`
"Company Name"
"Company Name Test"
"Company Name Test123"
...
...
...

`error`
" CompanyName"
"  CompanyName"
"CompanyName "
"Company  Name"

**Comment by Phil91** [comment]
@MaximilianHauer we have a shared regex for the company name in place which is used in several places those are:

`POST: api/administration/companydata/companyCertificate`
`POST: api/administration/invitation`
`POST: api/administration/registration/network/partnerRegistration`
`GET: api/administration/registration/network/companies?page=0&amp;size=4`
`GET: api/administration/registration/applications?page=0&amp;size=4`
`GET: api/administration/registration/application/{applicationId}/companyDetailsWithAddress`
`GET: api/administration/registration/applicationsWithStatus?page=0&amp;size=15`

should we change the regex for all those places? In my opinion having a special regex only for this use case doesn't make sense. For your information the currently used regex is `@"^\d*?[A-Za-zÀ-ÿ]\d?([A-Za-z0-9À-ÿ-_+=.,:;!?'\x22&#@()]\s?){2,40}$"`

**Comment by MaximilianHauer** [comment]
as aligned the following logic is currently not present in the regex and shouldnt be added due to sideffects and as the reason are not obvious. 

> signs and symbols not used as one of the first three characters in the company name. These are:
> *(asterisk)
> =(equals sign)
> +(plus sign)
> #(hashtag)
> % (percent sign)
> (space)
