### ISSUE TITLE
sig#803: API Enhancement - Deletion of External Technical Users

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#809]
reference ticket: https://github.com/eclipse-tractusx/portal-backend/issues/593

**Description:**
Existing service account deletion functionality to be extended allowing the deletion of technical users that are flagged as external. The current endpoint `DELETE /api/administration/serviceaccount/owncompany/serviceaccounts/{serviceAccountId}` should be utilized for this purpose.

**Acceptance Criteria:**
1. Extend the current deletion endpoint to check for the external flag on the technical user.
2. Depending if the flag is "external" or "internal" a different delete process will get followed.
  2a. for "internal" the process stays as is
  2b. for "external" a now backend logic will get followed (process followed below with # 3 ff.)
3. Run the external delete endpoint and wait for response
4. Upon receiving the successful delete response, set the technical user inside the portal DB to "DELETED" and update "lastChanged" date as well as "last editor" (table.identities)
5. API response: success

**Non-Functional requirements**
A. The system should log all deletion attempts, successful or otherwise.
B. Ensure that the audit function works for the API enhancement

**API Changes:**
- No changes to the endpoint path or method.

**Error Handling (should be already in place!):**
- If the technical user does not exist, return a 404 Not Found error.
- If the 3rd party system is not able to delete the technical user return a 404 error

**Comment by MaximilianHauer** [comment]
discussed to change status from `INACTIVE` to `DELETED` for technical users after the feedback was given by the dim.

**Comment by Phil91** [comment]
> discussed to change status from `INACTIVE` to `DELETED` for technical users after the feedback was given by the dim. Story to be enhanced to furthermore set the status directly to `DELETED` if the user is a synchronous technical user.

@MaximilianHauer just came across one case we didn't specified and wanted to mention it here. if for some reason the creation process of an external technical user is still in progress we now would cancel this progress and set the status of the user to `DELETED` directly without setting it to `DELETION_PENDING`. You can see this in my documentation pr as well.

**Comment by MaximilianHauer** [comment]
if the creation process is still ongoing we would need to raise an error during the call of the delete api.
this ensures that we would not cancel an unfinished process and the endcustomer can delete the technical user only as soon as the whole chain is fullfilled.

**Comment by MaximilianHauer** [comment]
tested successfully
