### ISSUE TITLE
Remove Provider Name from App Service Endpoints and Database Attribute

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#811]
**Description:**
The purpose of this ticket is to remove the 'provider' attribute currently in use throughout the app service endpoints and within the 'offers' database table. The reliance on the 'provider' name should be replaced by using the 'provider_company_id' which references the 'companies' table where the company name is stored. This change involves both database schema updates and modifications to the application's backend logic to ensure a smooth transition and continued functionality.

**Acceptance Criteria:**
1. Remove the 'provider' field from the 'offers' table in the database.
2. Update all backend services and endpoints that currently utilize the 'provider' field to instead use 'provider_company_id' for lookups.
3. Ensure that the 'companies' table and its 'name' field are correctly referenced wherever the provider's name is required.
4. Refactor any code, queries, or stored procedures that use 'provider' to adhere to the new schema.
5. Update all affected API responses to ensure consistency and avoid breaking changes for front-end services.
6. Conduct a thorough search to confirm that no legacy code remains that references the old 'provider' attribute.
7. Test all endpoints for functionality to confirm that the correct company names are retrieved and displayed. `//please test all the app controller endpoint which include a name, companyName or providerName`

**Technical Implementation:**
- Create a migration script to remove the 'provider' column from the 'offers' table.
- Update the application's data access layer to stop referring to 'offers.provider' and use 'offers.provider_company_id' with a join to 'companies' to retrieve the 'name'.
- Modify any business logic that depends on the 'provider' field.
- Search for and refactor any API endpoints that include the 'provider' field in the response.
- Update unit tests and integration tests to reflect the changes in the database schema and application logic.

**API Changes:**
- please ensure that this change has no impact on the API payload

**Comment by MaximilianHauer** [comment]
@ntruchsess please take over

**Comment by Phil91** [comment]
@MaximilianHauer already developed that one and created a pr.
@ntruchsess fyi
