### ISSUE TITLE
sig#796: SD / Clearinghouse toggle - enable job to retrigger

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#813]
**Ticket Description:**
This ticket outlines the implementation of two backend functionalities to enhance the management of SD (SelfDescription) documents within our system. The first is the creation of a GET API endpoint, and the second is the implementation of a job that can be triggered by administrators.

**Objectives:**

1. **GET API Endpoint**:
   - Create two new GET API endpoint to retrieve detailed information about missing SD documents.
   - This endpoint must provide the number of missing SD documents, along with customer information for the company record and connectors.
   - Ensure proper authentication and authorization checks are in place to secure the endpoint. (permission available below)
   - Ensure that only active companies will get fetched as well as only active connectors
Connector

GET: /api/administration/connectors/missing-sd-document?page=0&size=15

```json
{
  "meta": {
    "totalElements": 0,
    "totalPages": 0,
    "page": 0,
    "contentSize": 0
  },
  "content": [
    {
      "connectorId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string",
      "companyId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "companyName": "string"
    }
  ]
}
```

Company

GET: /api/administration/companyData/missing-sd-document?page=0&size=15

```json
{
  "meta": {
    "totalElements": 0,
    "totalPages": 0,
    "page": 0,
    "contentSize": 0
  },
  "content": [
    {
      "companyId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string"
    }
  ]
}
```

in addition to that we would have two endpoints to retrigger the self description creation:

Connector

POST: /api/administration/connectors/trigger-self-description

Company

POST: /api/administration/companyData/trigger-self-description

2. **Administrator-Triggered Job**:
   - Develop a job that can be initiated by an administrator with the 'approve_new_partner' permission.
   - The job should automatically trigger the SD creation process for all business partners lacking SD documentation.
   - Implement the necessary logic to handle cases where the company account or connector might not be in the expected state, ensuring that the job can handle or report errors gracefully.

**Acceptance Criteria:**

1. The GET API endpoint must:
   - Respond with a list of all companies and connectors missing SD documents.
   - Only care for ACTIVE companies/connectors
   - Include the total count of connectors with missing SD documents.
   - Be executable only by users with the 'approve_new_partner' permission.
   - Provide clear and concise information about the customer and company records.

2. The administrator-triggered job must:
   - Be executable only by users with the 'approve_new_partner' permission.
   - Successfully initiate the SD creation process for all eligible business partners.
   - For each company without a sd document a separate process should be created
   - For each connector without a sd document a separate process should be created

**Notes:**
- The callback mechanism for the SD document creation process is not yet defined. This needs to be considered during the implementation and may require a flexible design to accommodate future changes.
- Ensure that the implementation includes unit tests and integration tests to validate the functionalities.
- Documentation should be updated to reflect the new API endpoint and the job's operation.

**Implementation Steps:**

1. Design the API endpoint, defining the necessary routes, parameters, and response format.
2. Implement the logic for the GET API endpoint in the backend system.
3. Create the necessary authentication and authorization controls for the new endpoint.
4. Design and implement the job for SD creation, ensuring it includes proper permission checks.
5. Implement error handling and logging mechanisms for the job.
6. Write tests for both the endpoint and the job to ensure they work as expected.
7. Update the system documentation to include information about the new functionalities.
8. Review the implementation with the team and incorporate any feedback.

**Comment by jjeroch** [comment]
As soon as starting the task, discussion by dev and PO needed

**Comment by jjeroch** [comment]
@Phil91 please dont forget to initiate a discussion before PR creation

**Comment by Phil91** [comment]
@jjeroch could you set up a meeting for the both of us to discuss this topic?

**Comment by Phil91** [comment]
@jjeroch @MaximilianHauer my suggestion would be to split the get endpoint into two endpoints, one for company and one for connectors. This would result in the following:

**Connector**

GET: /api/administration/connectors/missing-sd-document?page=0&size=15

response json
```json
{
  "meta": {
    "totalElements": 0,
    "totalPages": 0,
    "page": 0,
    "contentSize": 0
  },
  "content": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string",
      "companyId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "companyName": "string"
    }
  ]
}
```

**Company**

GET: /api/administration/companyData/missing-sd-document?page=0&size=15

```json
{
  "meta": {
    "totalElements": 0,
    "totalPages": 0,
    "page": 0,
    "contentSize": 0
  },
  "content": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string"
    }
  ]
}
```

in addition to that we would have two endpoints to retrigger the self description creation:

**Connector**

POST: /api/administration/connectors/trigger-self-description


**Company**

POST: /api/administration/companyData/trigger-self-description

if that's okay like that I would create the PR with the mentioned changes

**Comment by MaximilianHauer** [comment]
as aligned looks good for me. trigger will then handle both apis sequentially.
@jjeroch  any feedback/doubts ?

**Comment by Phil91** [comment]
@jjeroch if the mentioned changes are okay, I'd set the PR to active :) if any changes are needed I'll adjust the draft pr.

@MaximilianHauer fyi

**Comment by jjeroch** [comment]
> @jjeroch if the mentioned changes are okay, I'd set the PR to active :) if any changes are needed I'll adjust the draft pr.
> 
> @MaximilianHauer fyi

Yes agree

**Comment by MaximilianHauer** [comment]
tested and approved
