### ISSUE TITLE
Inviting a new partner fails in the create Realm in Shared IdP step

### ISSUE THREAD

**Issue by gomezbc** [eclipse-tractusx/portal-backend#814]
I am currently trying to understand the process of boarding a new partner into a self hosted dataspace.

### Current Behavior
When i try to invite a partner through the invitation interface, the umbrella-portal-processes-worker fails to create the realm in the Shared IdP.

I get the following logs:
[logs-from-keycloak-in-umbrella-sharedidp-0.log](https://github.com/user-attachments/files/15969876/logs-from-keycloak-in-umbrella-sharedidp-0.log)
[logs-from-umbrella-portal-processes-worker-in-umbrella-portal-processes-worker-manual-79k-56pfb.log](https://github.com/user-attachments/files/15969877/logs-from-umbrella-portal-processes-worker-in-umbrella-portal-processes-worker-manual-79k-56pfb.log)

Realm in the Shared Idp is successfully created.
![Screenshot 2024-06-25 at 13-01-18 Keycloak Administration UI](https://github.com/eclipse-tractusx/portal-backend/assets/77118356/87cfe608-3248-46f4-a5b6-0a8e7282d999)

Also, invites tables remains with 0 row, experiencing a similar issue as #579 

![Screenshot 2024-06-25 at 13-04-28 Catena-X Portal](https://github.com/eclipse-tractusx/portal-backend/assets/77118356/eb44966e-d4ab-4770-8a77-7c1cdb6f5a4a)

### Expected Behavior
The umbrella-portal-processes-worker shouldn't fail to create the realm and it should continue with the invitation process. 

### Steps To Reproduce
I'm using firefox 127.0.1 in Ubuntu 22.04 and in a minikube cluster and i'm using Portal helm chart version 2.0.0 and, Centralidp and Sharedidp versions 3.0.0.

**Comment by evegufy** [comment]
Hi @gomezbc as the umbrella helm chart is not yet upgraded to the versions which you mention in the issue (which are the ones from the 24.05 release, the umbrella helm chart is still on the 24.3 release), I assume that you did the configuration for those versions on your own 👍  I assume you might have missed to provide valid encryption keys, as the default autogenerated keys are not valid ones: here you find a complete configuration for the relevant versions: https://github.com/eclipse-tractusx/portal/blob/localdev-portal-iam-0.6.1/charts/localdev/values.yaml

**Comment by gomezbc** [comment]
Thanks @evegufy, you are right, i tried to update dependencies and values to 24.05 and i missed to set encryption keys. I closed this issue because i found #787 which explains how to solve it.

Thanks for the help.
