### ISSUE TITLE
sig#802: Validate Retrigger Process Worker Possibilities with Endpoint Mapping

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#816]
### Description:
The goal is to validate the retriggering capabilities for each step in our backend processes and to document the specific endpoint to be used for retriggering. This detailed mapping will allow for the enhancement of our frontend status endpoints, which currently lack the exact retrigger endpoint information.

### Tasks:
1. Validate the retriggering possibility for each process step.
2. Document the corresponding retrigger endpoint for each retriggerable step.
3. Update the status endpoints to include this retrigger endpoint mapping for frontend integration.

### Acceptance Criteria:
- Each process step is assessed for retriggering capability.
- A list is provided with the retriggerable steps and their corresponding endpoints (input see below)
- Status endpoints are updated with accurate retrigger endpoint mapping.

### List of Process Worker Steps

| Step Name                                      | Retrigger Possible | Retrigger Endpoint                    |
|------------------------------------------------|--------------------|---------------------------------------|
| VERIFY_REGISTRATION                            |                    |                                       |
| CREATE_BUSINESS_PARTNER_NUMBER_PUSH           |                    |                                       |
| CREATE_BUSINESS_PARTNER_NUMBER_PULL           |                    |                                       |
| CREATE_BUSINESS_PARTNER_NUMBER_MANUAL         |                    |                                       |
| CREATE_IDENTITY_WALLET                        |                    |                                       |
| RETRIGGER_IDENTITY_WALLET                     |                    |                                       |
| START_CLEARING_HOUSE                          |                    |                                       |
| RETRIGGER_CLEARING_HOUSE                      |                    |                                       |
| END_CLEARING_HOUSE                            |                    |                                       |
| START_SELF_DESCRIPTION_LP                     |                    |                                       |
| RETRIGGER_SELF_DESCRIPTION_LP                 |                    |                                       |
| ACTIVATE_APPLICATION                          |                    |                                       |
| RETRIGGER_BUSINESS_PARTNER_NUMBER_PUSH        |                    |                                       |
| RETRIGGER_BUSINESS_PARTNER_NUMBER_PULL        |                    |                                       |
| OVERRIDE_BUSINESS_PARTNER_NUMBER              |                    |                                       |
| TRIGGER_OVERRIDE_CLEARING_HOUSE               |                    |                                       |
| START_OVERRIDE_CLEARING_HOUSE                 |                    |                                       |
| FINISH_SELF_DESCRIPTION_LP                    |                    |                                       |
| DECLINE_APPLICATION                           |                    |                                       |
| CREATE_DIM_WALLET                             |                    |                                       |
| AWAIT_DIM_RESPONSE                            |                    |                                       |
| RETRIGGER_CREATE_DIM_WALLET                   |                    |                                       |
| VALIDATE_DID_DOCUMENT                         |                    |                                       |
| RETRIGGER_VALIDATE_DID_DOCUMENT               |                    |                                       |
| REQUEST_BPN_CREDENTIAL                        |                    |                                       |
| STORED_BPN_CREDENTIAL                         |                    |                                       |
| REQUEST_MEMBERSHIP_CREDENTIAL                 |                    |                                       |
| STORED_MEMBERSHIP_CREDENTIAL                  |                    |                                       |
| TRANSMIT_BPN_DID                              |                    |                                       |
| RETRIGGER_TRANSMIT_DID_BPN                    |                    |                                       |
| TRIGGER_PROVIDER                              |                    |                                       |
| START_AUTOSETUP                               |                    |                                       |
| OFFERSUBSCRIPTION_CLIENT_CREATION             |                    |                                       |
| SINGLE_INSTANCE_SUBSCRIPTION_DETAILS_CREATION |                    |                                       |
| OFFERSUBSCRIPTION_TECHNICALUSER_CREATION      |                    |                                       |
| ACTIVATE_SUBSCRIPTION                         |                    |                                       |
| TRIGGER_PROVIDER_CALLBACK                     |                    |                                       |
| RETRIGGER_PROVIDER                            |                    |                                       |
| RETRIGGER_OFFERSUBSCRIPTION_CLIENT_CREATION   |                    |                                       |
| RETRIGGER_OFFERSUBSCRIPTION_TECHNICALUSER_CREATION |               |                                       |
| RETRIGGER_PROVIDER_CALLBACK                   |                    |                                       |
| TRIGGER_ACTIVATE_SUBSCRIPTION                 |                    |                                       |
| OFFERSUBSCRIPTION_CREATE_DIM_TECHNICAL_USER   |                    |                                       |
| RETRIGGER_OFFERSUBSCRIPTION_CREATE_DIM_TECHNICAL_USER |            |                                       |
| AWAIT_CREATE_DIM_TECHNICAL_USER_RESPONSE      |                    |                                       |
| RETRIGGER_AWAIT_CREATE_DIM_TECHNICAL_USER_RESPONSE |               |                                       |
| SYNCHRONIZE_USER                              |                    |                                       |
| RETRIGGER_SYNCHRONIZE_USER                    |                    |                                       |
| TRIGGER_CALLBACK_OSP_SUBMITTED                |                    |                                       |
| TRIGGER_CALLBACK_OSP_APPROVED                 |                    |                                       |
| TRIGGER_CALLBACK_OSP_DECLINED                 |                    |                                       |
| RETRIGGER_CALLBACK_OSP_SUBMITTED              |                    |                                       |
| RETRIGGER_CALLBACK_OSP_APPROVED               |                    |                                       |
| RETRIGGER_CALLBACK_OSP_DECLINED               |                    |                                       |
| MANUAL_DECLINE_OSP                            |                    |                                       |
| REMOVE_KEYCLOAK_USERS                         |                    |                                       |
| RETRIGGER_REMOVE_KEYCLOAK_USERS               |                    |                                       |
| SEND_MAIL                                     |                    |                                       |
| RETRIGGER_SEND_MAIL                           |                    |                                       |
| INVITATION_CREATE_CENTRAL_IDP                 |                    |                                       |
| INVITATION_CREATE_SHARED_IDP_SERVICE_ACCOUNT  |                    |                                       |
| INVITATION_ADD_REALM_ROLE                     |                    |                                       |
| INVITATION_CREATE_SHARED_REALM                |                    |                                       |
| INVITATION_CREATE_CENTRAL_IDP_ORG_MAPPER      |                    |                                       |
| INVITATION_UPDATE_CENTRAL_IDP_URLS            |                    |                                       |
| INVITATION_CREATE_SHARED_CLIENT               |                    |                                       |
| INVITATION_ENABLE_CENTRAL_IDP                 |                    |                                       |
| INVITATION_CREATE_DATABASE_IDP                |                    |                                       |
| INVITATION_CREATE_USER                        |                    |                                       |
| RETRIGGER_INVITATION_CREATE_CENTRAL_IDP       |                    |                                       |
| RETRIGGER_INVITATION_CREATE_SHARED_IDP_SERVICE_ACCOUNT |            |                                       |
| RETRIGGER_INVITATION_ADD_REALM_ROLE           |                    |                                       |
| RETRIGGER_INVITATION_CREATE_SHARED_REALM      |                    |                                       |
| RETRIGGER_INVITATION_CREATE_CENTRAL_IDP_ORG_MAPPER |               |                                       |
| RETRIGGER_INVITATION_UPDATE_CENTRAL_IDP_URLS  |                    |                                       |
| RETRIGGER_INVITATION_CREATE_SHARED_CLIENT     |                    |                                       |
| RETRIGGER_INVITATION_ENABLE_CENTRAL_IDP       |                    |                                       |
| RETRIGGER_INVITATION_CREATE_USER              |                    |                                       |
| RETRIGGER_INVITATION_CREATE_DATABASE_IDP      |                    |                                       |
| CREATE_DIM_TECHNICAL_USER                     |                    |                                       |
| RETRIGGER_CREATE_DIM_TECHNICAL_USER           |                    |                                       |
| DELETE_CENTRAL_USER                           |                    |                                       |
| RETRIGGER_DELETE_CENTRAL_USER                 |                    |                                       |
| DELETE_COMPANYUSER_ASSIGNED_PROCESS           |                    |                                       |
| DELETE_IDP_SHARED_REALM                       |                    |                                       |
| RETRIGGER_DELETE_IDP_SHARED_REALM             |                    |                                       |
| DELETE_IDP_SHARED_SERVICEACCOUNT              |                    |                                       |
| RETRIGGER_DELETE_IDP_SHARED_SERVICEACCOUNT    |                    |                                       |
| DELETE_CENTRAL_IDENTITY_PROVIDER              |                    |                                       |
| RETRIGGER_DELETE_CENTRAL_IDENTITY_PROVIDER    |                    |                                       |
| DELETE_IDENTITY_PROVIDER                      |                    |                                       |

**Comment by jjeroch** [comment]
as part of this ticket implementations are expected to take place; additionally the outcome is an input for https://github.com/eclipse-tractusx/portal-assets/issues/351

**Comment by jjeroch** [comment]
add a info regarding "who is able to retrigger" the process.
As soon as we have those details, we can check if endpoints can get merged...however dont forget to check with FE since we have an extended FE logic implemented which is quite important

**Comment by Phil91** [comment]
@jjeroch here the information:


| Step Name                                              | Retrigger Possible | Retrigger Endpoint                                                                                                              |
|--------------------------------------------------------|--------------------|---------------------------------------------------------------------------------------------------------------------------------|
| VERIFY_REGISTRATION                                    |         NO         |                                                                                                                                 |
| CREATE_BUSINESS_PARTNER_NUMBER_PUSH                    |         YES        | api/administration/registration/application/{applicationId}/trigger-bpn                                                         |
| CREATE_BUSINESS_PARTNER_NUMBER_PULL                    |         YES        | api/administration/registration/application/{applicationId}/trigger-bpn                                                         |
| CREATE_BUSINESS_PARTNER_NUMBER_MANUAL                  |         NO         |                                                                                                                                 |
| CREATE_IDENTITY_WALLET                                 |         YES        | api/administration/registration/application/{applicationId}/trigger-identity-wallet                                             |
| RETRIGGER_IDENTITY_WALLET                              |         NO         |                                                                                                                                 |
| START_CLEARING_HOUSE                                   |         YES        | api/administration/registration/application/{applicationId}/retrigger-clearinghouse                                             |
| RETRIGGER_CLEARING_HOUSE                               |         NO         |                                                                                                                                 |
| END_CLEARING_HOUSE                                     |         NO         |                                                                                                                                 |
| START_SELF_DESCRIPTION_LP                              |         YES        | api/administration/registration/application/{applicationId}/trigger-self-description                                            |
| RETRIGGER_SELF_DESCRIPTION_LP                          |         NO         |                                                                                                                                 |
| ACTIVATE_APPLICATION                                   |         NO         |                                                                                                                                 |
| RETRIGGER_BUSINESS_PARTNER_NUMBER_PUSH                 |         NO         |                                                                                                                                 |
| RETRIGGER_BUSINESS_PARTNER_NUMBER_PULL                 |         NO         |                                                                                                                                 |
| OVERRIDE_BUSINESS_PARTNER_NUMBER                       |         NO         |                                                                                                                                 |
| TRIGGER_OVERRIDE_CLEARING_HOUSE                        |         NO         |                                                                                                                                 |
| START_OVERRIDE_CLEARING_HOUSE                          |         YES        | api/administration/registration/application/{applicationId}/override-clearinghouse                                              |
| FINISH_SELF_DESCRIPTION_LP                             |         NO         |                                                                                                                                 |
| DECLINE_APPLICATION                                    |         NO         |                                                                                                                                 |
| CREATE_DIM_WALLET                                      |         YES        | api/administration/registration/application/{applicationId}/retrigger-create-dim-wallet                                         |
| AWAIT_DIM_RESPONSE                                     |         NO         |                                                                                                                                 |
| RETRIGGER_CREATE_DIM_WALLET                            |         NO         |                                                                                                                                 |
| VALIDATE_DID_DOCUMENT                                  |         YES        | api/administration/registration/application/{applicationId}/retrigger-validate-did                                              |
| RETRIGGER_VALIDATE_DID_DOCUMENT                        |         NO         |                                                                                                                                 |
| REQUEST_BPN_CREDENTIAL                                 |         NO         |                                                                                                                                 |
| STORED_BPN_CREDENTIAL                                  |         NO         |                                                                                                                                 |
| REQUEST_MEMBERSHIP_CREDENTIAL                          |         NO         |                                                                                                                                 |
| STORED_MEMBERSHIP_CREDENTIAL                           |         NO         |                                                                                                                                 |
| TRANSMIT_BPN_DID                                       |         YES        | missing                                                                                                                         |
| RETRIGGER_TRANSMIT_DID_BPN                             |         NO         |                                                                                                                                 |
| TRIGGER_PROVIDER                                       |         YES        |api/administration/subscriptionconfiguration/process/offer-subscription/{offerSubscriptionId}/retrigger-provider-callback        |
| START_AUTOSETUP                                        |         NO         |                                                                                                                                 |
| OFFERSUBSCRIPTION_CLIENT_CREATION                      |         YES        |api/administration/subscriptionconfiguration/process/offer-subscription/{offerSubscriptionId}/retrigger-create-client            |
| SINGLE_INSTANCE_SUBSCRIPTION_DETAILS_CREATION          |         NO         |                                                                                                                                 |
| OFFERSUBSCRIPTION_TECHNICALUSER_CREATION               |         YES        |api/administration/subscriptionconfiguration/process/offer-subscription/{offerSubscriptionId}/retrigger-create-technical-user    |
| ACTIVATE_SUBSCRIPTION                                  |         NO         |                                                                                                                                 |
| TRIGGER_PROVIDER_CALLBACK                              |         YES        |api/administration/subscriptionconfiguration/process/offer-subscription/{offerSubscriptionId}/retrigger-provider-callback        |
| RETRIGGER_PROVIDER                                     |         NO         |                                                                                                                                 |
| RETRIGGER_OFFERSUBSCRIPTION_CLIENT_CREATION            |         NO         |                                                                                                                                 |
| RETRIGGER_OFFERSUBSCRIPTION_TECHNICALUSER_CREATION     |         NO         |                                                                                                                                 |
| RETRIGGER_PROVIDER_CALLBACK                            |         NO         |                                                                                                                                 |
| TRIGGER_ACTIVATE_SUBSCRIPTION                          |         NO         |                                                                                                                                 |
| OFFERSUBSCRIPTION_CREATE_DIM_TECHNICAL_USER            |         YES        |missing                                                                                                                          |
| RETRIGGER_OFFERSUBSCRIPTION_CREATE_DIM_TECHNICAL_USER  |         NO         |                                                                                                                                 |
| AWAIT_CREATE_DIM_TECHNICAL_USER_RESPONSE               |         YES        |missing                                                                                                                          |
| RETRIGGER_AWAIT_CREATE_DIM_TECHNICAL_USER_RESPONSE     |         NO         |                                                                                                                                 |
| SYNCHRONIZE_USER                                       |         YES        |api/administration/registration/network/{externalId}/retrigger-synchronize-users                                                 |
| RETRIGGER_SYNCHRONIZE_USER                             |         NO         |                                                                                                                                 |
| TRIGGER_CALLBACK_OSP_SUBMITTED                         |         YES        |api/administration/registration/network/{externalId}/retrigger-callback-osp-submitted                                            |
| TRIGGER_CALLBACK_OSP_APPROVED                          |         YES        |api/administration/registration/network/{externalId}/retrigger-callback-osp-approve                                              |
| TRIGGER_CALLBACK_OSP_DECLINED                          |         YES        |api/administration/registration/network/{externalId}/retrigger-callback-osp-decline                                              |
| RETRIGGER_CALLBACK_OSP_SUBMITTED                       |         NO         |                                                                                                                                 |
| RETRIGGER_CALLBACK_OSP_APPROVED                        |         NO         |                                                                                                                                 |
| RETRIGGER_CALLBACK_OSP_DECLINED                        |         NO         |                                                                                                                                 |
| MANUAL_DECLINE_OSP                                     |         NO         |                                                                                                                                 |
| REMOVE_KEYCLOAK_USERS                                  |         YES        |missing                                                                                                                          |
| RETRIGGER_REMOVE_KEYCLOAK_USERS                        |         NO         |                                                                                                                                 |
| SEND_MAIL                                              |         YES        |missing                                                                                                                          |
| RETRIGGER_SEND_MAIL                                    |         NO         |                                                                                                                                 |
| INVITATION_CREATE_CENTRAL_IDP                          |         YES        |api/administration/invitation/{processId}/retrigger-create-central-idp                                                           |
| INVITATION_CREATE_SHARED_IDP_SERVICE_ACCOUNT           |         YES        |api/administration/invitation/{processId}/retrigger-create-shared-idp-sa                                                         |
| INVITATION_ADD_REALM_ROLE                              |         YES        |missing                                                                                                                          |
| INVITATION_CREATE_SHARED_REALM                         |         YES        |api/administration/invitation/{processId}/retrigger-create-shared-realm-idp-client                                               |
| INVITATION_CREATE_CENTRAL_IDP_ORG_MAPPER               |         YES        |api/administration/invitation/{processId}/retrigger-create-central-idp-org-mapper                                                |
| INVITATION_UPDATE_CENTRAL_IDP_URLS                     |         YES        |api/administration/invitation/{processId}/retrigger-update-central-idp-urls                                                      |
| INVITATION_CREATE_SHARED_CLIENT                        |         YES        |missing                                                                                                                          |
| INVITATION_ENABLE_CENTRAL_IDP                          |         YES        |api/administration/invitation/{processId}/retrigger-enable-central-idp                                                           |
| INVITATION_CREATE_DATABASE_IDP                         |         YES        |api/administration/invitation/{processId}/retrigger-create-database-idp                                                          |
| INVITATION_CREATE_USER                                 |         YES        |api/administration/invitation/{processId}/retrigger-create-user                                                                  |
| RETRIGGER_INVITATION_CREATE_CENTRAL_IDP                |         NO         |                                                                                                                                 |
| RETRIGGER_INVITATION_CREATE_SHARED_IDP_SERVICE_ACCOUNT |         NO         |                                                                                                                                 |
| RETRIGGER_INVITATION_ADD_REALM_ROLE                    |         NO         |                                                                                                                                 |
| RETRIGGER_INVITATION_CREATE_SHARED_REALM               |         NO         |                                                                                                                                 |
| RETRIGGER_INVITATION_CREATE_CENTRAL_IDP_ORG_MAPPER     |         NO         |                                                                                                                                 |
| RETRIGGER_INVITATION_UPDATE_CENTRAL_IDP_URLS           |         NO         |                                                                                                                                 |
| RETRIGGER_INVITATION_CREATE_SHARED_CLIENT              |         NO         |                                                                                                                                 |
| RETRIGGER_INVITATION_ENABLE_CENTRAL_IDP                |         NO         |                                                                                                                                 |
| RETRIGGER_INVITATION_CREATE_USER                       |         NO         |                                                                                                                                 |
| RETRIGGER_INVITATION_CREATE_DATABASE_IDP               |         NO         |                                                                                                                                 |
| CREATE_DIM_TECHNICAL_USER                              |         YES        |missing                                                                                                                          |
| RETRIGGER_CREATE_DIM_TECHNICAL_USER                    |         NO         |                                                                                                                                 |
| DELETE_CENTRAL_USER                                    |         YES        |api/administration/registration/{processId}/retrigger-delete-centraluser                                                         |
| RETRIGGER_DELETE_CENTRAL_USER                          |         NO         |                                                                                                                                 |
| DELETE_COMPANYUSER_ASSIGNED_PROCESS                    |         NO         |                                                                                                                                 |
| DELETE_IDP_SHARED_REALM                                |         YES        |api/administration/registration/{processId}/retrigger-delete-idpSharedRealm                                                      |
| RETRIGGER_DELETE_IDP_SHARED_REALM                      |         NO         |                                                                                                                                 |
| DELETE_IDP_SHARED_SERVICEACCOUNT                       |         YES        |api/administration/registration/{processId}/retrigger-delete-idpSharedServiceAccount                                             |
| RETRIGGER_DELETE_IDP_SHARED_SERVICEACCOUNT             |         NO         |                                                                                                                                 |
| DELETE_CENTRAL_IDENTITY_PROVIDER                       |         YES        |                                                                                                                                 |
| RETRIGGER_DELETE_CENTRAL_IDENTITY_PROVIDER             |         NO         |api/administration/registration/{processId}/retrigger-delete-centralIdentityProvider                                             |
| DELETE_IDENTITY_PROVIDER                               |         NO        |                                                                                                                                  |
