### ISSUE TITLE
Service Manager User | Service Management -> Admin Board | 403 Forbidden

### ISSUE THREAD

**Issue by tfjanjua** [eclipse-tractusx/portal-backend#831]
### Current Behavior
`Service Management` -> `Admin Board` page is not showing the Services and responding 403 Forbidden error.

### Expected Behavior
`Service Manager` should be able to see services list on `Admin Board` page OR `Service Manager` should not see `Admin Board` sub-menu option under `Service Management` menu if Service Manager doesn't supposed to have related permissions.

### Steps To Reproduce
- Login to the portal as a Service Manager
- Mouse Hover on Service Management menu and click on Admin Board option

### Findings
`Service Management` -> `Admin Board` page is calling the API: https://portal-backend.entry.cofinity-x.com/api/services/serviceRelease/inReview?size=15&page=0&status=InReview&sorting=DateDesc

and this API has following permissions: 

- approve_service_release
- decline_service_release

but `Service Manager` user account doesn’t have such permissions, I can share `Service Manager` user account’s access token and its existing list of permissions, if required.

**Comment by tfjanjua** [comment]
@evegufy  | @jjeroch  
I couldn't find above mentioned `approve_service_release` and `decline_service_release` into the permission's matrix
https://github.com/eclipse-tractusx/portal-assets/blob/v2.0.0/public/assets/images/content/PortalRoleAndPermissionMatrix.png

**Comment by tfjanjua** [comment]
Assigned this ticket to @evegufy to get her input, if she also reproduced this issue.

**Comment by evegufy** [comment]
Hi @tfjanjua thank you for opening the issue!
Yes, there's appears to be an issue with the documentation but in general they are available as client roles of the Portal client:
- [approve_service_release](https://github.com/eclipse-tractusx/portal-iam/blob/v3.0.0/import/realm-config/generic/catenax-central/CX-Central-realm.json#L849)
- [decline_service_release](https://github.com/eclipse-tractusx/portal-iam/blob/v3.0.0/import/realm-config/generic/catenax-central/CX-Central-realm.json#L1180)

and assigned to CX Admin composite role:
[assigned approve_service_release](https://github.com/eclipse-tractusx/portal-iam/blob/v3.0.0/import/realm-config/generic/catenax-central/CX-Central-realm.json#L1331)
[assigned decline_service_release](https://github.com/eclipse-tractusx/portal-iam/blob/v3.0.0/import/realm-config/generic/catenax-central/CX-Central-realm.json#L1339)

But from business process perspective it seems correct to me that only the CX Admin would be allowed to approve or decline App Releases. Does that help as input?

**Comment by tfjanjua** [comment]
Hi @evegufy , thanks for you quick response and sharing the existence of roles.

I also think that assigned roles from CX Admin point of view are correct but here the issue is with Service Manager type of user that Service Manager doesn't have those approve or decline service release roles so, either Service Manager should be able to see services list on Admin Board page OR Service Manager should not see Admin Board sub-menu option under Service Management menu if Service Manager doesn't supposed to have related permissions.

Because if you see the API which I have mentioned under the Findings heading, that has approve and decline service release roles and this API is to get services data so, do you think that those approve and decline roles are appropriate for a GET type of API which is getting the Released Services data.

I am assuming there would be other and separate APIs which would approve and decline any released service and I feel that these approve and decline roles would be appropriate for those separate approve and decline APIs.

But my whole point would be invalid if Service Manager type of user is not supposed to see IsReview services and if so, then we can think to hide Service Management -> Admin Board sub-menu for a Service Manager user role.

**Comment by evegufy** [comment]
Hi @tfjanjua yes, the Service Manager is not supposed to approve or decline service releases, so to not show the submenu in the frontend appears the proper solution, maybe this applies also to App Manager, could you please check and open an issue in the frontend repo?
We'll make sure that the roles are added to the permission matrix.

**Comment by tfjanjua** [comment]
This issue was created on backend repo with the assumption that this issue could be resolved from backend side but the issue needs to be resolved from the frontend side so, I am closing it because I have opened another issue on frontend https://github.com/eclipse-tractusx/portal-frontend/issues/936

FYI @evegufy : this issue exists only for Service Manager user and there no such issue for App Manager user.
