### ISSUE TITLE
sig#796: Ensure Application Status Endpoints Reflect Clearinghouse Feature Toggle Effects

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#837]
## Description:
Following the implementation changes detailed in [issue #792](https://github.com/eclipse-tractusx/portal-backend/issues/792), this ticket addresses the need to verify and potentially update how the application status endpoints are functioning. The recent addition of the feature toggle to enable or disable Clearinghouse connectivity for Self-Description (SD) processes requires that the endpoints accurately reflect the state of each application process step.

## Objectives:
- Verify the behavior of the GET application status endpoints after the toggle changes.
- Update the status representation in the endpoints to appropriately reflect the skipping or non-applicability of steps due to the feature toggle being enabled or disabled.
- Include a comment or notation within the status to explain the reason for any skipped steps to maintain transparency and support auditing requirements.

## Acceptance Criteria:
- **Endpoint Verification**: The GET application status endpoints must be thoroughly tested to ensure they are behaving as expected after the toggle implementation.
- **Status Updates**: If the clearinghouse connectivity is disabled, the endpoints should indicate the affected steps as "n/a" (not applicable) or equivalent, rather than omitting them.
- **Audit Support**: Each step that is skipped due to the toggle being enabled should include a comment detailing the reason, aiding in clarity and audit trails.
- **Documentation**: Ensure that endpoint documentation is updated to reflect the new status representations and the logic behind any changes.

**Comment by jjeroch** [comment]
Refinement ongoing: application_checklist status "Skipped" likely needed

**Comment by jjeroch** [comment]
Moved to next (interim release) 24.08. closed
New sprint: 02

**Comment by MaximilianHauer** [comment]
@Phil91 could you adjust the following documentation based on our adjustments ? https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/user/01.%20Onboarding/03.%20Registration%20Approval/03.%20Registration%20Approval%20Process.md

**Comment by MaximilianHauer** [comment]
tested and approved
