### ISSUE TITLE
Adjust "Consortia" Seeding File Names to "Test" Seeding File

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#840]
**Description:**
The current seeding files for the "Consortia" feature are named in a way that may not clearly indicate their purpose as test data. We need to rename these files to reflect that they are for testing environments and ensure they are segregated from release seed files.

---

**Acceptance Criteria:**

1. All seeding files currently named with the "consortia" prefix should be renamed with the "test" prefix.
2. Successfully tested the change
3. The renamed files are ideally located in a separate directory from production seed files to prevent accidental seeding in production environments.
4. Update all references to the "consortia" seeding files in the codebase to the new "test" prefixed file names.
5. Ensure that the seeding process still functions correctly after the file renaming, without any errors or data issues.
6. The changes should be documented, and the team should be informed of the new naming convention.

---

**Proposed Test Cases:**

*Seeding Process Test:*
   - Execute the seeding process with the renamed test files to ensure that there are no errors and the data is seeded as expected.
   - Confirm that the seeding process does not affect production databases and is isolated to the test environment.

**Comment by evegufy** [comment]
consortia seeding files should be removed with the end of consortia
