### ISSUE TITLE
sig#809: API Enhancement OSP Customer Management -  GET /api/administration/registration/network/companies Endpoint

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#850]
**Description:**
The current endpoint `GET /api/administration/registration/network/companies` requires enhancements to both the response body and functionality. The following changes need to be implemented:

1. **Response Body Enhancements:**
   - Add `externalID` field to the response body to represent the external identifier of the company.
   - Add `dateCreated` field to the response body to represent the creation date of the company record.

2. **New Search Functionalities:**
   - Implement the ability to search by `companyName` to allow users to find companies more efficiently.
   - Implement the ability to search by `externalID` to facilitate lookup using external identifiers.

3. **New Sort Functionalities:**
   - Implement sorting by `dateCreated` in both ascending (ASC) and descending (DESC) order.

**Acceptance Criteria:**
- The response body should include the new fields `externalID` and `dateCreated`.
- The API should support query parameters for searching by `companyName` and `externalID`.
- The API should support query parameters for sorting by `dateCreated` in both ASC and DESC order.
- Ensure that all existing functionalities are maintained and that the new features do not introduce any regressions.
- Update the API documentation to reflect the new changes.
- Write unit tests to cover the new functionalities and update existing tests as necessary.

**Response Body Example (updated):**

```json
{
  "meta": {
    "totalElements": 0,
    "totalPages": 0,
    "page": 0,
    "contentSize": 0
  },
  "content": [
    {
      "companyId": "uuid",
      "externalID": "string",
      "applicationId": "uuid",
      "applicationStatus": "CREATED",
      "applicationDateCreated": "2024-06-24T19:43:59.670Z",
      "dateCreated": "2024-06-24T19:43:59.670Z",
      "lastChangedDate": "2024-06-24T19:43:59.670Z",
      "companyName": "string",
      "companyRoles": [
        "ACTIVE_PARTICIPANT"
      ],
      "identityProvider": [
           {
              "id": "uuid",
              "name": "aliasName"
          }
       ],
      "bpn": "string",
      "activeUsers": "{countActiveOrCreatedCompanyUsers}",
    }
  ]
}
```

**Implementation Notes:**
- Ensure to follow the existing coding standards and architecture.
- Review the existing endpoint to understand current functionalities.

**Comment by MaximilianHauer** [comment]
@AnuragNagpure  please ensure to create a new PR for this that enables @lavanya-bmw  to proceed with her frontend adjustments based on the previos ticket from you.

**Comment by ntruchsess** [comment]
to change the sorting-order a new optional query-parameter 'dateCreatedOrderFilter' (Values 'ASC', 'DESC') has been introduced

**Comment by AnuragNagpure** [comment]
> to change the sorting-order a new optional query-parameter 'dateCreatedOrderFilter' (Values 'ASC', 'DESC') has been introduced

Thanks Norbert for this new sorting order
