### ISSUE TITLE
sig#796: Explore CH runtime activation for CH Compliance Activation During Approval Flow

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#855]
`Ticket under refinement`

### Description
The previously implemented runtime toggle for the deactivation/activation of the Clearinghouse Compliance flow (CH) enabled the administrators to enable or disable CH validation. Its expected that this toggle works without any disruption for ongoing processes.
As part of this ticket the possible interruption for registrations (companies as well as connectors) need to get validated, best solved and not possible to be solved scenarios need to get documented for the operation of the solution.

### Objectives

1. **Seamless Transition**:
   - Develop logic to handle the transition of registrations from a state where CH is disabled to a state where CH is enabled and vice versa.
   - Ensure that the transition is seamless and does not negatively impact the user experience or the integrity of the approval flow.

### Acceptance Criteria

1. The transition logic must:
   - Ensure that registrations in the approval flow continue seamlessly when CH is enabled or disabled.
   - Handle any edge cases that might occur due to the state change to prevent data inconsistencies or user errors.

### Notes
- Detailed technical documentation is required to guide the implementation and future maintenance of this feature.

### Implementation Steps

1. Analyze and document the current approval flow to identify points of impact when CH is toggled.
2. Develop transition logic that maintains the integrity of the approval flow during a toggle state change.
3. Update the system documentation with detailed information on how the toggle works and its impact on the approval flow.

**Comment by MaximilianHauer** [comment]
@Phil91  explained that this is currently already implemented.
implicitly implemented already.
