### ISSUE TITLE
App Release | App manager is allowed to upload duplicate roles

### ISSUE THREAD

**Issue by tfjanjua** [eclipse-tractusx/portal-backend#868]
There are multiple issues occurring at Technical Integration step

### Issue# 1
Users are allowed to upload the same CSV file with same Role values any number of times, resulting in the same roles being repeated multiple times in the app's role list.

**Current Behavior:** Same role being repeated n times in the list and also does not allow to delete the role.

**Expected Behavior:** It should ignore the duplicate role and also deletion of each recently uploaded should be working.

**Steps To Reproduce:**
1. Login to the Portal as App Manager
2. Register an App
3. Add/Input all the required data
4. Under Technical integration --> Download the CSV template and then upload it
5. Delete the recently uploaded CSV template and Upload it again (N Times)

### Issue# 2
When User deletes the uploaded file of roles then uploaded roles are not removing from the list.

**Current Behavior:** Uploaded file removed successfully but it’s associated roles remain as it is and due to that duplication of roles is happening in the section.

**Expected Behavior:** Roles file should be deleted and it’s associated roles should be removed.

**Steps To Reproduce:**
1. Login to the Portal as App Manager
2. Register an app
3. Add/Input all the required data
4. Under Technical integration --> Download CSV template and then upload it back
5. Delete the recently uploaded CSV template

### Proposed Solutions

1. While Onboarding a New App: At Technical Integration step
**Backend**: API exists to upload the App Roles but backend would need to change the API and ignore the duplicate role values while uploading the roles to the server
**Frontend**: Frontend can also check the Roles values and eliminate the duplicate values before sending them to the backend OR stop user sending request unless user did not remove the duplicate values

2. While Onboarding a New App: Delete all roles which were recently uploaded by .csv file
**Backend**: Backend would need to create a new API which will accept the list of recently uploaded role Ids and eventually will delete the roles from the database
**Frontend**: Frontend would be integrating this API and passing all the recently uploaded role's IDs to the API to delete the roles

3. While Onboarding a New App: Delete one recently uploaded role at a time
**Backend**: API exists but currently returning 400 so, backend would need to check whats the issue
**Frontend**: For the time being, no change is required

4. While updating the Onboarded App: Delete all the roles which were recently uploaded by .csv file
**Backend**: Same API mentioned in point# 1 can be used here as well
**Frontend**: Frontend would have to identify the recently uploaded roles (because in case of update, already assigned roles would already be part of app) and then pass the recently uploaded role Ids to the API to delete them from the database

5. Load Additional Roles to any Active App:
**Backend**: API exists to load additional roles but backend would have to update the API and check the duplicate values to ignore them
**Frontend**: For the time being, no change is required

**Comment by ntruchsess** [comment]
@MaximilianHauer we need to decide whether the upload of roles should not result in pure insert but completely define the set of roles doing all create/update/delete at once.
current PR #877 attempts to avoid creation of duplicates when the insert-endpoint is being called and adds an additional endpoint that allows to delete roles. That would require adaptions in the FE to allow selection of to-be-deleted roles.

**Comment by MaximilianHauer** [comment]
@tfjanjua your new api changes would force us to adjust the frontend too. 
had a discussion with @ntruchsess  and we would propose a solution that does not implement a new deletion api but does update the existing roles based on the new file.
please connect to @ntruchsess

**Comment by ntruchsess** [comment]
Issue 1 in this ticket is resolved by PR #877
The proposed solution for Issue 2 (endpoint is not deleting roles) there existing endpoint should be changed in such way that it allways does adjust the roles in the database to match the uploaded ones.
- it should create uploaded roles (including description) that do not yet exist in the db
- it should adjust (that means create/update/delete) descriptions of roles that are already existing in the db according to the uploaded roles
- it should delete roles and their descriptions that are existing in the database, but not in the uploaded set of roles

**Comment by MaximilianHauer** [comment]
as we solved the urgent needs we can now focus on following the proper way for the second adjustment.
as this is changing business functionality the proper way is to register the change in the next release planning of the association. 
Please follow the process https://catenax-ev.github.io/docs/next/working-model/process-structure/issue-process#create-new-feature-inside-sig-release and link the frontend/backend related stories to the sig-release feature request
