### ISSUE TITLE
Decline Registration | 'First and Last Name' Column Blank on Invite Request page

### ISSUE THREAD

**Issue by dhiren-singh-007** [eclipse-tractusx/portal-backend#871]
### Current Behavior
If a user declines its invite application then First and Last name shows blank in Invite page in frontend.

### Expected Behavior
First and last name should be shown even if user declines the registration

### Steps To Reproduce

1. Register on the portal application using credential in invite email.
2. Decline the registration
3. Check the status on ‘Invite a new partner’ page.

### RCA:
After declining the registration user got deactivated and hence api returns null for name fields

**Comment by MaximilianHauer** [comment]
retested and works
