### ISSUE TITLE
How to pass alternative address

### ISSUE THREAD

**Issue by anjuchaurasiya** [eclipse-tractusx/portal-backend#872]
### Current Behavior

Please let us know what information in need to pass in the form to avoid this error bcoz we dont see such field available on the form while registering the user : [TaskErrorDto(type=Unspecified, description=Alternative Address has no country)]

### Expected Behavior

The new user should be registered without any issue

**Comment by evegufy** [comment]
Hi @anjuchaurasiya it's not a portal issue, you need to upgrade to BPDM Patch version https://github.com/eclipse-tractusx/bpdm/pull/983, [chart version 5.0.3](https://github.com/eclipse-tractusx/bpdm/tree/bpdm-5.0.3)

**Comment by anjuchaurasiya** [comment]
Thank you @evegufy :)
