### ISSUE TITLE
[E2E Test 24.08] Missing notification events and info emails

### ISSUE THREAD

**Issue by ds-hzimmer** [eclipse-tractusx/portal-backend#878]
### Current Behavior
This issue is a collection of several identified missing notification events and/or info emails encountered during the execution of test cases for the 24.08 Portal release

**1. Welcome - Notification to new user**
Info emails with content "Welcome to Catena-X - Your User Account got created" (as well as "Registration Request Approved" for the company) were successfully received. 
But no notification was received in the "Notifications" sub-menu after login to the Portal.

**2. App Subscription - Info email to provider**
No identifiable email notification received as the provider of the app after a customer request for an app subscription, respectively after approving a subscription.

Only to the customer that a subscription request for [App name] got successfully approved, deployed, and the application is ready to use.

**3. Service Release - Info email to requesting user**
No identificable email notification received that a request for a service Release was successfully approved.

### Expected Behavior

1. Welcome - Notification to new user
According to test case "CPLP-1827 Welcome Notification" (CXTM-215), a "welcome" notification should also be visible in the "Notifications" sub-menu when a new user logs into the portal. 

Thus to be determined by product responsible if this notification in the portal is planned/implemented in addition to the successful email that gets sent out, or test needs to be adapted or removed.

2. App Subscription - Info email to provider
According to test case "CPLP-1091 App Subscription - Request App Subscription (Customer) - Provider Email" (CXTM-218), the expected action would be to "validate if the app provider has received the email notification" with expected result "email notification received and URL is working". 

Thus to be determined if either a missing email notification according to planned/implemented notification events, or test needs to be adapted or removed.

3. Service Release - Info email to requesting user
According to test case "TEST-1060 Portal - Service Release InfoMail (CXTM-20), the expected action would be to "check that the user who requested Service Release receive an Email informing them of the approval".

Thus to be determined if either a missing email notification according to planned/implemented notification events, or test needs to be adapted or removed.

### Steps To Reproduce
Tested with deployed version for release 24.08 (2.1.0-RC2)

Mailserver sender address: testenv-notification@catena-x.net which was newly created for the Catena-X INT environment for release 24.08

Tested with companies "Test Management" respectively "CX-Operator" to approve requests.

Notifications expected for triggered processes as described above in behavior.

**Comment by MaximilianHauer** [comment]
@ds-hzimmer please retest in int :)

**Comment by evegufy** [comment]
@ds-hzimmer as discussed, I'll close this issue. Please create a new issue with the topics that you didn't retest successfully and new topics you discovered in the course of the e2e testing for R24.12-
