### ISSUE TITLE
Asynchron Tech Users - Portal Table Naming Review for Clarity and Consistency

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#879]
**Description:**
The UX Analyst is tasked with reviewing the current naming convention of the portal table used by external technical users. The table currently named "dim_technical_users" is not ideal as it includes the acronym "DIM" which refers to a specific application. This can cause confusion and limit the table's potential for reuse with future services. The task involves identifying a more appropriate and generic name that is not tied to a specific application and can accommodate asynchronous technical users for various services.

**Acceptance Criteria:**
1. Evaluate the current table name "dim_technical_users" and assess its implications for clarity and potential reuse.
2. Propose a list of alternative table names that do not include application-specific acronyms or terms.
3. Validate the proposed names with stakeholders to ensure they meet the needs of current and future services.
4. Update all references to the old table name in documentation, code, and any other relevant materials.
5. Conduct a final review to confirm that the new name is properly implemented across the platform.

**Comment by Phil91** [comment]
@MaximilianHauer I would propose the name `external_technical_users`. Since that's exactly what they are. technical users in a third party solution (external). If you're fine with that I'd start adjusting the naming

**Comment by Phil91** [comment]
discussed with @MaximilianHauer , we will rename the `dim_technical_users` to `external_technical_users and `company_service_accounts` to `technical_users`

@evegufy @ntruchsess  fyi
