### ISSUE TITLE
Users onboarded via OSP Flow can't login after successful onboarding process

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-backend#892]
### Current Behaviour
I've onboarded a company as an OSP. After submitting the OSP registration as the OSP user and running threw the registration process, the users of the onboarded company still have the role Cl1-CX-Registration -> Company Admin

### Expected Behavior
After onboarding the company and successfully running threw the registration process the user should have the roles Cl2-CX-Portal -> Company Admin

### Steps To Reproduce
The current problem is that within the OSP process the users are not added to the Invitations table, which is a problem since the ApplicationActivation gets the users for an application threw the invitations table and changes the roles of the user based on that

**Comment by MaximilianHauer** [comment]
@Phil91 this we tested together right ?

**Comment by Phil91** [comment]
@MaximilianHauer correct :)
