### ISSUE TITLE
Duplicate "subscriptionID" field in GET /owncompany/serviceaccounts/{serviceAccountId} endpoint

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#897]
**Environment:** 
- **URL:** `/api/administration/serviceaccount/owncompany/serviceaccounts/{serviceAccountId}`
- **Release Version:** unclear; likely since several releases

**Description:**
When calling the GET `/api/administration/serviceaccount/owncompany/serviceaccounts/{serviceAccountId}` endpoint, the response includes the "subscriptionID" field twice. According to the swagger documentation, "subscriptionID" should only appear once in the response.

**Steps to Reproduce:**
1. Authenticate with the necessary permissions to access the admin endpoint.
2. Send a GET request to `/api/administration/serviceaccount/owncompany/serviceaccounts/{serviceAccountId}` with a valid `{serviceAccountId}`.
3. Observe the response.

**Expected Result:**
The response JSON should contain the "subscriptionID" field only once.

**Actual Result:**
The response JSON contains the "subscriptionID" field twice.

**User Impact:**
The duplicated field may cause confusion and potentially lead to issues with systems or clients that consume this API and expect the response format to match the documentation.

**Comment by jjeroch** [comment]
Problem: this could be breaking

**Comment by Phil91** [comment]
@jjeroch we return the subscriptionId only once:

https://github.com/eclipse-tractusx/portal-backend/blob/df8be4a73cd12888f9a410eada400c019b6157ed/src/administration/Administration.Service/Models/ServiceAccountConnectorOfferData.cs#L28

![image](https://github.com/user-attachments/assets/d1a46ac8-ee59-4870-920c-e96630f9cbc8)

I think we can close this issue right?

@MaximilianHauer  fyi

**Comment by gopalreddy-bmw** [comment]
Hi @MaximilianHauer 
tested this US According to the requirements it's working fine.
Attached screenshots for references:
![image](https://github.com/user-attachments/assets/d29b0d90-d0b5-410f-b212-ec37f0511cda)
