### ISSUE TITLE
sig#796: Enhance SelfDescription retrigger process

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-backend#903]
To correctly support the clearinghouseConnectDisabled toggle the endpoint `POST: api/administration/registration/application/{applicationId}/trigger-self-description` needs to be adjusted as follows:

- if the toggle is true (connection to clearinghouse is disabled), the retrigger process should create the`ACTIVATE_APPLICATION` process step
- If the toggle is false, the retrigger process should create the `START_SELF_DESCRIPTION_LP` process step.

The application checklist item should than be set to `SKIPPED`

**Comment by MaximilianHauer** [comment]
tested and approved
