### ISSUE TITLE
sig#811 Enable Process Worker endpoints to be retriggered and add necessary steptype

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-backend#912]
### Description
**AS A** System 
**WHEN** a trigger fails
**THEN** i should be able to retrigger it to retry and proceed on the current step. 

Step   Name | Retrigger   Possible | Retrigger   Endpoint |  
-- | -- | -- | --
TRANSMIT_BPN_DID | YES | missing | phil:   endpoint needed to retrigger
REQUEST_BPN_CREDENTIAL | NO |   | phil:   retrigger endpoint and steptype needed
STORED_BPN_CREDENTIAL | NO |   | phil:   retrigger endpoint and steptype needed
REQUEST_MEMBERSHIP_CREDENTIAL | NO |   | phil:   retrigger endpoint and steptype needed
STORED_MEMBERSHIP_CREDENTIAL | NO |   | phil:   retrigger endpoint and steptype needed
OFFERSUBSCRIPTION_CREATE_DIM_TECHNICAL_USER | YES | missing | phil:   retrigger endpoint and steptype needed
AWAIT_CREATE_DIM_TECHNICAL_USER_RESPONSE | YES | missing | phil:   retrigger endpoint and steptype needed
REMOVE_KEYCLOAK_USERS | YES | missing | phil:   retrigger endpoint and steptype needed
SEND_MAIL | YES | missing | phil:   retrigger endpoint and steptype needed
INVITATION_ADD_REALM_ROLE | YES | missing | phil:   retrigger endpoint and steptype needed
INVITATION_CREATE_SHARED_CLIENT | YES | missing | phil:   retrigger endpoint and steptype needed
CREATE_DIM_TECHNICAL_USER | YES | missing | phil:   retrigger endpoint and steptype needed
DELETE_CENTRAL_IDENTITY_PROVIDER | YES |   | phil:   retrigger endpoint and steptype needed

### Acceptance Criteria

- [ ] Each process step is assessed for retriggering capability.
- [ ] Status endpoints are updated with accurate retrigger endpoint mapping
- [ ] The process worker documentation is updated with the retriggerable steps and their corresponding endpoints

**Comment by MaximilianHauer** [comment]
@Phil91 to be reviewed. if you provide feedback i would add these to the list or create a new ticket if the task defers 


TRANSMIT_BPN_DID | YES | missing | phil: endpoint   needed to retrigger
-- | -- | -- | --
DELETE_COMPANYUSER_ASSIGNED_PROCESS | NO |   | phil:   recheck
DELETE_IDENTITY_PROVIDER | NO |   | phil:   recheck
TRIGGER_ACTIVATE_SUBSCRIPTION | NO |   | phil:   recheck

**Comment by Phil91** [comment]
@ max for the mentioned three process steps we don't need a retrigger process :)
