### ISSUE TITLE
sig#809: Create API for Customeroverview of OSP Management Section

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-backend#914]
### Description

**As** an OSP
**I want** to see an overview of all my Companies i am onboarding including Name /Onboarding Status/ IDP Name / Usercount ,
**so that** i get a good overview on the current onboarding situation .

## propose endpoint
`GET:api/administration/registration/network/onboardedCompanies`
Role: `view_onboarded_companies`

### Acceptance Criteria

- [ ] Api can only get accessed with the role `view_onboarded_companies`
- [ ] Name of the company is visible
- [ ] Status of the onboarding is shown
- [ ] Name of IDP is visible 
- [ ] Amount of users of this onboarding is visible as count

**Comment by MaximilianHauer** [comment]
@Phil91  as this is preconditon to https://github.com/eclipse-tractusx/portal-frontend/issues/541 please set the PR to priority

**Comment by Phil91** [comment]
Closed because of duplication, see #850
