### ISSUE TITLE
Provide duplicate error message during connector creation

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-backend#917]
### Description

During the call of the following API 

`POST: /api/administration/connectors`
`POST: /api/administration/connectors/managed`

i want to receive a proper error message if the values of the fields `name`, `serviceAccount` and `connectorUrl` are existing already
The error message should clearly define that these entries are existing already and duplicates are not allowed.

### Acceptance Criteria

- [ ] post an existing `name` and receive a precise error message
- [ ] post an existing `serviceAccount` and receive a precise error message
- [ ] post an existing `connectorUrl` and receive a precise error message
- [ ] post a new `name` and receive a success message 
- [ ] post a new `serviceAccount` and receive a success message 
- [ ] post a new `connectorUrl` and receive a success message

**Comment by Phil91** [comment]
@MaximilianHauer fyi changed `POST: /api/administration/connectors/daps` to `POST: /api/administration/connectors`
