### ISSUE TITLE
Connector is created with wrong state

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-backend#918]
### Current Behavior
When creating a connector it is created with the wrong state. If the clearinghouseConnectDisabled is set to true the connector status is set to ACTIVE if the toggle is set to false it is set to PENDING.

### Expected Behavior
The connector status should be set as follows:

- clearinghouseConnectDisabled = true
  - ConnectorStatusId.PENDING
-  clearinghouseConnectDisabled = false
   - ConnectorStatusId.ACTIVE

### Steps To Reproduce
Create a connector with clearinghouseConnectDisabled = true

**Comment by evegufy** [comment]
Hi @Phil91 as we discussed that the change from https://github.com/eclipse-tractusx/portal-backend/pull/919 isn't wanted from business perspective, I'd would remove it from the release branch.
Please confirm that the following state, without the commit, is alright for you:
https://github.com/eclipse-tractusx/portal-backend/commits/chore/fix-2.2.0-RC2-release-branch/
I'd then force-with-lease the state to the release branch https://github.com/eclipse-tractusx/portal-backend/commits/release/v2.2.0-RC2

I also tested the state from https://github.com/eclipse-tractusx/portal-backend/commits/chore/fix-2.2.0-RC2-release-branch/ and the connector gets set to active in case of
- the company was onboarded and the connector gets registered with `clearinghouseconnectdisabled` toogle enabled
- he company was onboarded with `clearinghouseconnectdisabled` toogle diabled and the connector gets registered with `clearinghouseconnectdisabled` toogle enabled

![image](https://github.com/user-attachments/assets/9205ca87-7620-429a-9047-4bfec3019b02)

cc: @MaximilianHauer @jjeroch @ntruchsess

**Comment by Phil91** [comment]
> Hi @Phil91 as we discussed that the change from #919 isn't wanted from business perspective, I'd would remove it from the release branch. Please confirm that the following state, without the commit, is alright for you: https://github.com/eclipse-tractusx/portal-backend/commits/chore/fix-2.2.0-RC2-release-branch/ I'd then force-with-lease the state to the release branch https://github.com/eclipse-tractusx/portal-backend/commits/release/v2.2.0-RC2
> 
> I also tested the state from https://github.com/eclipse-tractusx/portal-backend/commits/chore/fix-2.2.0-RC2-release-branch/ and the connector gets set to active in case of
> 
> * the company was onboarded and the connector gets registered with `clearinghouseconnectdisabled` toogle enabled
> * the company was onboarded with `clearinghouseconnectdisabled` toogle diabled and the connector gets registered with `clearinghouseconnectdisabled` toogle enabled
> 
> ![image](https://private-user-images.githubusercontent.com/46191613/357465469-9205ca87-7620-429a-9047-4bfec3019b02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTU3NjksIm5iZiI6MTcyMzYxNTQ2OSwicGF0aCI6Ii80NjE5MTYxMy8zNTc0NjU0NjktOTIwNWNhODctNzYyMC00MjlhLTkwNDctNGJmZWMzMDE5YjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA2MDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNjAyNWRlNzgxYTNmNzE0NDgwOGEwNzJhZGRlMjY2ODczMGY2YWNiZDcwZjBiZjMwNTAwODU2NWE5ZTlkNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oE6jk5tR3lL_qL2MEDCmIgeEitI6axxzwrQphlb-ihM)
> 
> cc: @MaximilianHauer @jjeroch @ntruchsess

@evegufy thanks, looks good to me, in my opinion we can do the fix like that :)

**Comment by evegufy** [comment]
@Phil91 done

--> clone with WONT DO
