### ISSUE TITLE
Missing isOwnCompanyData in BPDM request payload

### ISSUE THREAD

**Issue by dhiren-singh-007** [eclipse-tractusx/portal-backend#927]
### Current Behavior
During company onboarding in BPN creation step BE is sending this flag `OwnCompanyData` to BPDM while as per their documentation flag name should be `isOwnCompanyData`
API of BPDM : `PUT: input/business-partners`

Specification of API Latest: [Latest : upsert-business-partners-input](https://eclipse-tractusx.github.io/docs-kits/next/kits/Business%20Partner%20Kit/Software%20Development%20View/Gate%20Api/upsert-business-partners-input)
Specification of API 24.05: [upsert-business-partners-input](https://eclipse-tractusx.github.io/docs-kits/24.05/kits/Business%20Partner%20Kit/Software%20Development%20View/Gate%20Api/upsert-business-partners-input)

### Expected Behavior
BE should send this flag `isOwnCompanyData` to BPDM .

### Steps To Reproduce
It can be checked directly in code 
Model is used is this 
```cs
public record BpdmLegalEntityData(
    string ExternalId,
    IEnumerable<string> NameParts,
    IEnumerable<BpdmIdentifier> Identifiers,
    IEnumerable<BpdmState> States,
    IEnumerable<string> Roles,
    BpdmLegalEntity LegalEntity,
    BpdmSite? Site,
    BpdmAddress Address,
    bool OwnCompanyData
);

**Comment by MaximilianHauer** [comment]
current documentation shows the same. 
if this is fine for @ntruchsess / @evegufy / @Phil91  i am too.

**Comment by Phil91** [comment]
> current documentation shows the same. if this is fine for @ntruchsess / @evegufy / @Phil91 i am too.

yes. makes absolutely sense to change it on our side. PR approved and merged
