### ISSUE TITLE
Operator | Send invites with custom technical user | Change of Access Policy

### ISSUE THREAD

**Issue by typecastcloud** [eclipse-tractusx/portal-backend#932]
### Description

**As** portal operator,
**I want** to access `api/administration/invitation` endpoint via technical user,
**so that** a valid operator company can provide clients to integrate external systems like hubspot.

Right now only portal user can use the endpoint.

### Acceptance Criteria

- [x] Technical user with correct operator bpn/organisation attribute and role `invite_new_partner` can send invites via `api/administration/invitation` endpoint.
- [ ] As CX Operator company I can create a technical user with the `invite_new_partner` role.

### Additional Information
[Authorize(Policy = PolicyTypes.CompanyUser)] -> [Authorize(Policy = PolicyTypes.ValidCompany)]

CC: @jjeroch @MaximilianHauer

**Comment by MaximilianHauer** [comment]
under clarification

**Comment by typecastcloud** [comment]
> under clarification

The Initial step would be to allow access to endpoint via technical user at all. Right now only portal user can access this. There is no technical user that has this role to send out invites, but we can configure a different technical user to have the role until there is one.
Adding a new technical user type that only CX Operator can create would be a second step.

But maybe you have a different proposal.

**Comment by MaximilianHauer** [comment]
@ntruchsess / @evegufy / @Phil91  lets discuss the options after your vacation

**Comment by MaximilianHauer** [comment]
@typecastcloud i would follow your idea regardin the creation of a technical_user that can be created by cx-operator. makes sense for me.

**Comment by typecastcloud** [comment]
> @typecastcloud i would follow your idea regarding the creation of a technical_user that can be created by cx-operator. makes sense for me.
> 
> please enhance the ticket with the respective acc-

Sorry I forgot to answer here. I'll create the separate PR for that and adjust the issue.

**Comment by MaximilianHauer** [comment]
Yeah would fit into the current setup :) 

proposal for the description: 
"Technical user to leverage the invitation API to integrate 3rd party software."
