### ISSUE TITLE
Registration | Company Name Change Not Reflecting Consistently

### ISSUE THREAD

**Issue by dhiren-singh-007** [eclipse-tractusx/portal-backend#942]
### Current Behavior
When inviting a Business Partner in CX Admin, the initial Company Name (e.g., ABC) was specified. However, during the company registration process via the access link provided in the invite email, the Company Name was changed to (e.g., XYZ). Despite the change being reflected correctly on the Business Partner invite page within CX Admin, it does not update uniformly on the company user side, where the original Company Name (ABC) remains visible when accessed through the user icon.

Additionally, the Company Name remains unchanged on the Catena-X Home Page.

### Expected Behavior
The Company Name displayed on the company user side should reflect the latest change made during the registration process. In this case, it should display "XYZ" after the Business Partner updates it during registration.

### Steps To Reproduce

1. Log in to CX Admin and initiate an invite for a Business Partner.
2. Specify Company Name as "ABC" during the initial invite setup.
3. Send the invite email containing access details to the Business Partner.
4. Business Partner accesses the registration link from the email and changes the Company Name to "XYZ" during the registration process.
5. Verify on the CX Admin side:
6. Check the Business Partner invite page in CX Admin. Note that the Company Name displayed reflects the change to "XYZ".
7. Verify on the company user side:
8. Click on the user icon associated with the invited Business Partner.
9. Observe that the Company Name displayed remains "ABC", instead of updating to "XYZ" as expected.
10. Verify on Catena-X Home Page.

Example screenshots:

1. Company invited as Neha -Email Template

2. On submit registration company name changed to Müller as shown 
![image](https://github.com/user-attachments/assets/7f9ebb7f-6a30-468c-b163-90f275802a28)

3. Now when company go to select company name in login screen , Central idp is still showing old company name 
![image](https://github.com/user-attachments/assets/fb95bdf5-be54-478b-8540-a9b34a8a0943)

4. Now company admin logged and open User icon as shown , it is still showing old company name 
![image](https://github.com/user-attachments/assets/6fcb3d80-7735-44d7-853d-4a0bb0d06736)

RCA : Old Company name is coming from display name and Organization mapper attribute which is part of IDP of that specific company.

**Comment by Phil91** [comment]
@dhiren-singh-007 in my opinion adding the calls to update the organisation for the users of the company and a call to update the org name on the shared idp should be fine, since they are only updates, if it fails while updating retriggering the api is just fine.

**Comment by dhiren-singh-007** [comment]
adding @MaximilianHauer

**Comment by Phil91** [comment]
> > @dhiren-singh-007 in my opinion adding the calls to update the organisation for the users of the company and a call to update the org name on the shared idp should be fine, since they are only updates, if it fails while updating retriggering the api is just fine.
> 
> Thanks @Phil91 , I am not sure if i understood your point completely. But i think this data is coming from Central IDP On login page company name is showing from the Display name as shown ![image](https://private-user-images.githubusercontent.com/144212607/360338795-8a1d5030-876b-47e0-ae90-d1c784b7f2ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTQzNTksIm5iZiI6MTcyNDY1NDA1OSwicGF0aCI6Ii8xNDQyMTI2MDcvMzYwMzM4Nzk1LThhMWQ1MDMwLTg3NmItNDdlMC1hZTkwLWQxYzc4NGI3ZjJmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwNjM0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03M2FmNDUzOTkxMTQ3ODZiYjVlMTI4MGFiNDE5NGQxZjE1ZGZmN2ZiMTcwY2RjZjUzZjlhYjM0N2Q2ZGRiNzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vYpETpHd1J9nlQ0LrBv-TXLkaeRJtU8oI4awErPSl4M)
> 
> And in Portal This is showing from token attribute "Organisation" which is defined via Mapper attribute in Identity provider for specific company as shown ![image](https://private-user-images.githubusercontent.com/144212607/360339526-cb6a7f86-5470-4678-92c5-02813830f9c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTQzNTksIm5iZiI6MTcyNDY1NDA1OSwicGF0aCI6Ii8xNDQyMTI2MDcvMzYwMzM5NTI2LWNiNmE3Zjg2LTU0NzAtNDY3OC05MmM1LTAyODEzODMwZjljMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwNjM0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGZhMGU1NGYxZjRhNjBkMzIyYTdlZWE5OGMyMjU2OTcyZGJiN2ZkODJkOWFhYzY0YTBhY2E5NWQ0OGIzODNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C8SpvfWJWK7dWFgEI9a64gUZPEteuwCpzJ-Jwx1II_E)
> 
> Eg: Lets say one user changed the company name and saved the address during registration and didn't continue further . Now when user will come again then that user will still see the old company name on login page. Because of this this i am thinking that we have to make this call on central IDP in this api `POST: application/{applicationId}/companyDetailsWithAddress` So that user will always see updated data.
> 
> I am thinking something like this for company name and same way for attribute mapper (most probably in this method only). And then call this in the above api. I am not sure which file i should add this code but i am still analyzing.
> 
> ```cs
>     public async Task UpdateCompanyNameIdentityProviders(string aliasName, string organisationName, CancellationToken cancellationToken)
>     {
>         var keycloak = _keycloakFactory.CreateKeycloakClient("central");
>         try
>         {
>             var identityProvider = await keycloak.GetIdentityProviderAsync(_settings.CentralRealm, aliasName, cancellationToken).ConfigureAwait(ConfigureAwaitOptions.None);
> 
>             identityProvider!.DisplayName = organisationName;
>             await keycloak.UpdateIdentityProviderAsync(_settings.CentralRealm, identityProvider!.Alias, identityProvider, cancellationToken).ConfigureAwait(ConfigureAwaitOptions.None);
>         }
>         catch (Exception ex)
>         {
>            throw ex;
>         }
>     }
> ```
> 
> Please share your thoughts

@dhiren-singh-007 you're right, the proposed method looks good for me. what is still missing in my opinion is a method to change the user attribute for all users that are assigned to the company:

![image](https://github.com/user-attachments/assets/fa977bab-db52-4918-8418-bc513ded5863)

**Comment by MaximilianHauer** [comment]
addin @oyo

**Comment by oyo** [comment]
Currently in the rename process only the DB records are updated not the Keycloak realm and display name. On frontend side we are showing the user data from the Keycloak token which contains the original company name. On FE we could trigger another call to the backend after each login but that it would be more efficient to fix the data in the one rename API call with one Keycloak API call from BE to BE instead of one additional call from FE to BE in every user session.

**Comment by dhiren-singh-007** [comment]
> @dhiren-singh-007 you're right, the proposed method looks good for me. what is still missing in my opinion is a method to change the user attribute for all users that are assigned to the company:

yes , i missed that point . Thanks for highlighting it. 
Yes then i think high level there would be three function as follows:

1. Call to update display name of IDP in Central Idp .
2. Call to update Organization Attribute of IDP in Central Idp.
3. Call to update all user's Organization attribute in Central IDP.

Now i will start working on this.

**Comment by dhiren-singh-007** [comment]
Hi @Phil91 , While implementing the solution, I found that the 3rd point is not needed. This is because when the Organization attribute of an Identity Provider (IDP) is updated in the central IDP, Keycloak triggers an internal event whenever a user associated with that IDP logs in. This event automatically updates the user’s attributes, including the Organization attribute, after their login.

**Comment by dhiren-singh-007** [comment]
@Phil91 : yeah i just checked and i think this is the configuration . IMO we can keep this always in force because if number of users are large then portal BE will have lot of network calls to update user attribute.
![image](https://github.com/user-attachments/assets/b4a6c6f6-fee4-461d-8f99-c2417d9864ac)
