### ISSUE TITLE
Create managed connectors maps wrong provider

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-backend#944]
### Current Behavior
When creating a managed connector via `POST: /api/administration/connectors/managed` the host company is set as the provider and the provider company is set as the host 

### Expected Behavior
The correct provider and host should be set

### Steps To Reproduce
- Create a managed connector for a subscription of another company
- Try to get the details of the connector via `GET: /api/administration/connectors/{connectorId}`

Switch the host and provider here: https://github.com/eclipse-tractusx/portal-backend/blob/de6f3f6fe7c01725e56b442eff1cb62967b95f91/src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs#L180

### Acceptance Criteria
- [x] Unit Tests are provided
- [x] Test is executed successfully
- [x] PR created and reviewed

**Comment by MaximilianHauer** [comment]
approved
