### ISSUE TITLE
Get connectors returns all connectors

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-backend#945]
### Current Behavior
When requesting connectors via `GET: /api/administration/connectors` with existing managed connectors, the managed connectors are returned as well.

### Expected Behavior
The endpoint should only return connectors of type `COMPANY_CONNECTOR`.

### Steps To Reproduce
- create a managed connector and an owned connector
- request the connectors via the endpoint
- managed connector is listed in the response

### Acceptance Criteria
- [ ] Unit Tests are provided
- [ ] Test is executed successfully
- [ ] PR created and reviewed

**Comment by MaximilianHauer** [comment]
@AnuragNagpure 

if i execute the swagger endpoint via the operator account i still receive other entries.
![image](https://github.com/user-attachments/assets/0b364adf-5da4-4ec3-9bd6-46f4e2662a83)

**Comment by MaximilianHauer** [comment]
approved
