### ISSUE TITLE
errroCode for ServiceAccountDeletion is missing a word

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-backend#952]
### Current Behavior

![image](https://github.com/user-attachments/assets/32de4c2c-1b06-4eda-84dc-088f801d0c2f)

### Expected Behavior

errroCode should be `SERVICE_ACCOUNT_NOT_FOUND_CONFLICT`

**Comment by Phil91** [comment]
@MaximilianHauer I've set the milestone to 2.2.0 because I already did it within the adjustments for the deletion process of the technical user
