### ISSUE TITLE
sig#803 - Deletion of technical user during connector deletion 

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-backend#967]
### Current Behavior

If i delete a connector i can currently select the option to delete the responding technical user. 
Currently the technical user is only set to `inactive` but this is wrong.

### Expected Behavior

If i approve to delete the connector which is linked to an external user then execute the identical logic as we have in place for the technical user deletion endpoint.

**Comment by MaximilianHauer** [comment]
@Phil91  i did create a tec user id `282fff21-741a-411a-ae69-cf79e95cb991` attached it to a connector - waited until the connector is active- deleted the connector but the tec user stays active.

**Comment by Phil91** [comment]
> @Phil91 i did create a tec user id `282fff21-741a-411a-ae69-cf79e95cb991` attached it to a connector - waited until the connector is active- deleted the connector but the tec user stays active.

@MaximilianHauer did the call to the backend has the flag deleteTechnicalUser set to true? I'd say it was missing or set to false and therefor it didn't work.

**Comment by MaximilianHauer** [comment]
tested
