### ISSUE TITLE
sig#789 -  API Expansion for Technical User Information

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-backend#976]
### Description:
Expand the GET technical user information API to include the usertypeof technical user (internal/external).
As an API Developer, I need to enhance the `GET` technical user information API to include the technical user type and service endpoint so that this information can be programmatically retrieved and utilized in various systems.

Endpoint to be adjusted -> `GET: api/administration/serviceaccount/owncompany/serviceaccounts`

Add Parameter `usertype` should display `internal` or `external`

Endpoint to be adjusted -> `GET: GET: api/administration/serviceaccount/owncompany/serviceaccounts/{GetServiceAccountId}`

Add Parameter `usertype` should display `internal` or `external`
table in database: `portal.dim_company_service_accounts` 
field: `authentication_service_url`
should be provided via the parameter `authenticationServiceUrl`in the api get call 

---

#### Acceptance Criteria:

- [ ] The API should return whether the technical user is `internal` or `external`.
- [ ] The API should provide the service endpoint associated with the technical user.
- [ ] The API changes must maintain backward compatibility with existing integrations.

----

**Test Case 1: Retrieve technical user information - Internal user**
- **Description:** Verify that the API returns the correct technical user information for an internal user.
- **Steps:**
  1. Make a GET request to the endpoint `api/administration/serviceaccount/owncompany/serviceaccounts`.
  2. Verify that the response includes the following fields:
     - `usertype`: "internal"
     - `authenticationServiceUrl`: valid URL
- **Expected Result:** The API should return the technical user information with the correct "internal"usertype and a valid `authenticationServiceUrl`.

**Test Case 2: Retrieve technical user information - External user**
- **Description:** Verify that the API returns the correct technical user information for an external user.
- **Steps:**
  1. Make a GET request to the endpoint `api/administration/serviceaccount/owncompany/serviceaccounts`.
  2. Verify that the response includes the following fields:
     - `usertype`: "external"
     - `authenticationServiceUrl`: valid URL
- **Expected Result:** The API should return the technical user information with the correct "external" usertype and a valid `authenticationServiceUrl`.

**Test Case 3: Retrieve technical user information by ID - Internal user**
- **Description:** Verify that the API returns the correct technical user information for an internal user when queried by ID.
- **Steps:**
  1. Make a GET request to the endpoint `api/administration/serviceaccount/owncompany/serviceaccounts/{GetServiceAccountId}`.
  2. Verify that the response includes the following fields:
     - `usertype`: "internal"
     - `authenticationServiceUrl`: valid URL
- **Expected Result:** The API should return the technical user information with the correct "internal" usertype and a valid `authenticationServiceUrl`.

**Test Case 4: Retrieve technical user information by ID - External user**
- **Description:** Verify that the API returns the correct technical user information for an external user when queried by ID.
- **Steps:**
  1. Make a GET request to the endpoint `api/administration/serviceaccount/owncompany/serviceaccounts/{GetServiceAccountId}`.
  2. Verify that the response includes the following fields:
     - `usertype`: "external"
     - `authenticationServiceUrl`: valid URL
- **Expected Result:** The API should return the technical user information with the correct "external" usertype and a valid `authenticationServiceUrl`.

**Comment by w2wewwww** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by Phil91** [comment]
@MaximilianHauer as clarified in the daily

- for the internal users we access a settings value with the configured url to the centralIdp. For external users we can take the database value

@AnuragNagpure fyi

**Comment by AnuragNagpure** [comment]
Below PR for adding AuthServiceUrl in portal repository is mentioned below
https://github.com/eclipse-tractusx/portal/pull/432
