### ISSUE TITLE
sig#803 - Technical Users in state PENDING_DELETION are not displayed

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-backend#989]
### Current Behavior
When requesting the Endpoint `GET: api/administration/serviceaccount/owncompany/serviceaccounts` without any filters only 'ACTIVE' and 'PENDING' users are returned, but no user in state 'PENDING_DELETION'

### Expected Behavior
Users in state 'PENDING_DELETION' are returned as well

### Steps To Reproduce
Delete a dim technical user in the frontend, reload the table with all selected. The user isn't visible anymore

**Comment by MaximilianHauer** [comment]
tested
